ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"
weka:
  cluster_name: jack-kr-weka-mcb
  major_version: "4"
  minor_version: "2"
  build_version: "9"
  patch_version: ".29-hcsf"
  download_url: "get.weka.io/dist/v1/pkg"
  download: false
  base_path: /root
  admin_user: admin
  admin_default_pass: admin
  admin_change_pass: "Changeme12!@"
  bin_type: tar
  host_num: "{{ groups['workers'] | length }}"
  net:
    conn: "dpdk"                    # dpdk or udp
    gateway: "192.168.0.1"
    ha1: 1
    ha2: 2
  backend:
    scb: true
    mcb: false
    net:
      type: "virtual"               # or physical
      ipaddr0: "192.168.0."
      ipaddr1: "192.168.1.17"
      ipaddr2: "192.168.1.18"
      ipaddr3: "192.168.1.19"
      ipaddr4: "192.168.1.20"
      ipaddr5: "192.168.1.21"
      data_plane: netdev2
  obs: true
  fs: true
  protocol:
    s3: false
    nfs: false
    smb: true
  client:
    smb: true
    nfs: false
    s3: false
    wekafs: false
    net:
      type: "virtual"               # or physical
      cores: 1
      ipaddr0: "192.168.0.6"
      ipaddr1: "192.168.1.6"
      ipaddr2: "192.168.1.7"
      ipaddr3: "192.168.1.8"
  tools:                                       # git clone https://github.com/weka/tools; cd tools ; git checkout v1.3.8
    name: tools
    major_version: 1
    minor_version: 3
    patch_version: 8
    download: false
    bin_type: tar.gz
  wsa:
    download_url: "get.weka.io/api/v1/wsa/4.2.9.28/"
  wma:
    download_url: "get.weka.io/api/v1/wms/1.2.2/"

