ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"


_minio:
  download: false
  client_bin: /usr/local/bin/mc
  client_install: yes
  client_url: https://dl.minio.io/client/mc/release/linux-amd64/mc
  client_checksum:
  release_date: 20240307


_weka:
  cluster_name: jack-kr-weka-mcb
  major_version: "4"
  minor_version: "4"
  build_version: "3"
  patch_version: "" # ".28"
  download_url: "get.weka.io/dist/v1/pkg"
  download: false
  base_path: /opt
  admin_user: admin
  admin_default_pass: admin
  admin_change_pass: "Changeme12!@"
  bin_type: tar
  host_num: "{{ groups['workers'] | length }}"
  nvme: true
  net:
    conn: "dpdk"                    # dpdk or udp
    gateway: "192.168.0.1"
    ha1: 1
    ha2: 2
  backend:
    scb: false
    mcb: true
    net:
      type: "virtual"               # or physical
      ipaddr0: "192.168.0.17"
      ipaddr1: "192.168.1.17"
      ipaddr2: "192.168.1.18"
      ipaddr3: "192.168.1.19"
      ipaddr4: "192.168.1.20"
      ipaddr5: "192.168.1.21"
      ipaddr6: "192.168.2.17"
      data_plane: netdev2
  obs: true
  fs: true
  protocol:
    smb: true
    nfs: false
    s3: false
  client:
    smb: true
    nfs: false
    s3: false
    wekafs: true
    net:
      type: "virtual"               # or physical
      cores: 1
      ipaddr0: "192.168.0.17"
      ipaddr1: "192.168.1.17"
      ipaddr2: "192.168.1.18"
      ipaddr3: "192.168.1.19"
      ipaddr4: "192.168.1.20"
      ipaddr5: "192.168.1.21"
      ipaddr6: "192.168.2.17"
  ext_storage:
    net:
      ipaddr0: "192.168.0."
      ipaddr1: "192.168.1."
      ipaddr2: "192.168.2."
  tools:                                       # git clone https://github.com/weka/tools; cd tools ; git checkout v1.3.8
    name: tools
    major_version: 1
    minor_version: 3
    patch_version: 8
    download: false
    bin_type: tar.gz
  wsa:
    download_url: "get.weka.io/api/v1/wsa/4.2.9.28/"
  wma:
    download_url: "get.weka.io/api/v1/wms/1.2.2/"
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02", "rk9-node03", "rk9-node04", "rk9-node05", "rk9-node06", "rk9-node07" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05" ]


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"


kvm:
  hostname: "192.168.0.101"
  username: "root"
  password: "changeme"

