# weka smb cluster containers remove --container-ids 0,1,2,3,4 --force
#

#
- name: Leave from AD
  shell: |
    weka smb domain leave Administrator Changeme12\!\@
  register: leave_ad
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ leave_ad }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Destroy SMB Cluster
  shell: |
    weka smb cluster destroy -f
  register: destroy_smb_cluster
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

- debug: msg={{ destroy_smb_cluster }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

