---
- name: Set Up an Alias for MinIO to Interact With the Weka S3 Backend
  shell: |
    /usr/local/bin/mc alias set {{ item.mc_alias }} http://{{ feip }}:{{ _s3.endpoint.port }} {{ item.access_key }} {{ item.secret_key }} --api "s3v4" --path "on"
  register: set_mc_alias
  ignore_errors: true
  with_items: "{{ _s3.users }}"
- debug: msg={{ set_mc_alias }}
  when: print_debug == true


- name: Delete Parquet Test Files in Weka S3 Backends
  shell: |
    /usr/local/bin/mc rm --recursive --force {{ item.mc_alias }}/{{ item.bucket }}/
  register: delete_parquet_files
  ignore_errors: true
  with_items: "{{ _s3.users }}"
- debug: msg={{ delete_parquet_files }}
  when: print_debug == true


- name: Delete S3-Base Test Directory
  file:
    path: "{{ _s3.base_path }}/s3-base"
    state: absent
  register: delete_s3base_dir
  ignore_errors: true
- debug: msg={{ delete_s3base_dir }}
  when: print_debug == true


- name: Delete MC Hidden Directory
  file:
    path: "{{ _s3.base_path }}/.mc"
    state: absent
  register: delete_mc_dir
  ignore_errors: true
- debug: msg={{ delete_mc_dir }}
  when: print_debug == true

