#
#
- name: Delete Custom WekaFS with the specific capacity
  shell: |
    weka fs delete {{ wekafs.fs }} -f
  register: delete_custom_wekafs
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ delete_custom_wekafs }}


- name: Delete Custom WekaFS Group
  shell: |
    weka fs group delete {{ wekafs.group }}
  register: delete_wekafs_group
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ delete_wekafs_group }}

#
- name: Check Custom WekaFS
  shell: |
    weka fs
  register: check_custom_wekafs
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ check_custom_wekafs }}

#
- name: Check WekaFS in the containers
  shell: |
    weka cluster container
  register: check_wekafs_container
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ check_wekafs_container }}
