# ./wekachecker 192.168.0.{181..190}

# shell: yum-config-manager --enable devel
# export PDSH_RCMD_TYPE='ssh'

# weka local ps ; weka local stop
- name: Check if MCB and SCB both are enabled to deploy in groups_vars/all.yml
  fail: msg="Stopped due to both MCB and SCB settings enabled in groups_vars/all.yml. Please choose one of them and rerun playbook"
  when: weka.backend.mcb == true and weka.backend.scb == true

# It's not working although default container is OK
- name: Create SCB Container
  shell: |
    weka local setup container --name {{ container.default.name }}
  register: create_scb_cont
  when: setup_weka_bin == false and inventory_hostname in groups['workers']
- debug: msg={{ create_scb_cont }}
  when: setup_weka_bin == false and inventory_hostname in groups['workers']
  # weka local resources -C default memory {{ container.default.mem_size }}
  # weka local setup container --name {{ container.default.name }} --base-port {{ container.default.port }} \
  # --cores {{ container.total_cores }} --memory {{ container.default.mem_size }}
 
#
- name: Create Weka Cluster With All Hosts and Management IP Addresses
  shell: |
    weka cluster create {{ all_ext1_hostnames }} --host-ips={{ all_net5_ipaddrs }} -T infinite
  register: create_weka_cluster
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ create_weka_cluster }}
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
  #  weka cluster create {{ all_management_ipaddrs }}

#
- name: Validate if Weka Cluster is still creating
  shell: weka status
  register: check_apply_status
  until: check_apply_status.stderr.find("Make sure weka is running on this host by running") == -1
  retries: 30
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ check_apply_status }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Get All Container IDs and Hostnames
  shell:
    weka cluster container | awk '{print $1","$2}' | sed 1d
  register: all_cont_ids0
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ all_cont_ids0 }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Set Array Facts for All Container IDs and Hostnames
  set_fact:
    all_cont_ids: "{{ all_cont_ids | default([]) + [item.split(',')] }}"
  with_items:
    - "{{ all_cont_ids0.stdout_lines }}"
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ all_cont_ids  }}
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Delegate each Facts into Host matched with Container ID
  set_fact:
    cont_id: "{{ item[0] }}"
    cont_host: "{{ item[1] }}"
  delegate_to: "{{ item[1] }}"
  delegate_facts: True
  register: test1
  with_items:
    - "{{ all_cont_ids }}"
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ test1 }}
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Print Container ID
  debug: msg={{ cont_id }}
  when: inventory_hostname in groups['workers']

#
- name: Print Container Hostname
  debug: msg={{ cont_host }}
  when: inventory_hostname in groups['workers']


# https://stackoverflow.com/questions/75812817/converting-list-to-list-of-dictionaries-in-ansible-adding-constant-fields-using
# https://serverfault.com/questions/988278/converting-two-lists-into-a-specific-dictionary-so-it-can-be-sorted
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#combining-and-selecting-data
# all_cont_ids: "{{ all_container_ids.stdout_lines | map('trim') | map('split',' ') }}"
# all_cont_ids: "{{ all_container_ids.stdout_lines | split(',') | list }}"
# all_cont_ids: "{{ all_container_ids.stdout_lines | map('split',' ')}}"
# all_cont_ids: "{{ all_container_ids.stdout_lines | trim | split(',') | combine( { item.split(',')[0] : item.split(',')[1] } ) | list }}"
# - debug: "{{ all_netinfo | default([]) | combine(cont_ids, netinfo) }}"
# - debug: "{{ netinfo | map(cont_ids) | list }}"
# - debug: "{{ netinfo | product(all_cont_ids) | list }}"
# - debug: "{{ netinfo | zip( netinfo | map('extract', dict(all_cont_ids) ) | list ) }}"
# - debug: "{{ all_cont_ids | zip( all_cont_ids | map('extract', dict(netinfo) ) | list ) }}"
# - debug: "{{ all_cont_ids | zip(netinfo) | sort(attribute='0') | map(attribute='1') | list }}"
# - debug: "{{ netinfo | combine(cont_ids, recursive=true) }}"
# - debug: msg={{ all_cont_ids | map('extract', ["{{ netdev2 }}", "{{ netdev3 }}", "{{ netdev4 }}", "{{ netdev5 }}"]) | list }}
# - debug: msg={{ all_cont_ids | combine( [ netdev2 , netdev3 , netdev4 ,  netdev5 ], list_merge='append' ) }}
#
#- set_fact:
#    host_network_info: "{{ dict( [ netdev2, netdev3, netdev4, netdev5 ] | zip( all_cont_ids )) | dict2items(key_name='cont_id', value_name='netdev') }}"
#  debug: msg={{ dict([ netdev1, netdev2, netdev3, netdev4 ] | zip([ ipaddr1, ipaddr2, ipaddr3, ipaddr4, ipaddr5 ])) | dict2items( key_name='netdev', value_name='ipaddr' ) }} + {{ all_cont_ids }}

#- name: How to append item to a exited list
#  set_fact:
#    cont_ids: >-
#      {%- set results = [] -%}
#      {%- for item in all_cont_ids -%}
#      {%-   set _ = results.append({ 'cont_id': item, 'option': '' }) -%}
#      {%- endfor -%}
#      {{ results }}

#
- name: Set Facts to combine netdevs and ipaddrs
  set_fact:
    netinfo: "{{ dict([ netdev1, netdev2, netdev3, netdev4 ] | zip([ ipaddr1, ipaddr2, ipaddr3, ipaddr4 ])) | dict2items( key_name='netdev', value_name='ipaddr' ) }}"
  when: inventory_hostname in groups['workers']

#
- name: Add Networks Adpters into Container for DPDK Support
  shell: |
    weka cluster host net add {{ cont_id }} {{ item.netdev }} --ips {{ item.ipaddr }} --netmask 24
  register: add_network_drive
  with_items:
    - "{{ netinfo }}"
  when: weka.net.conn == "dpdk" and inventory_hostname in groups['workers']
- debug: msg={{ add_network_drive }}
  when: print_debug == true and weka.net.conn == "dpdk" and inventory_hostname in groups['workers']
  # --gateway 192.168.1.1
  # deletate also works
  # delegate_to: "{{ hostvars[groups['workers'][0]]['ansible_hostname'] }}"
  # delegate_facts: True

#
- name: Delete Partition Table
  shell: |
    dd if=/dev/zero of=/dev/vdb bs=512 count=1; dd if=/dev/zero of=/dev/vdc bs=512 count=1;
    wipefs --all --force /dev/vdb; wipefs --all --force /dev/vdc;
  register: del_part_table
  when: inventory_hostname in groups['workers']
- debug: msg={{ del_part_table }}
  when: print_debug == true and inventory_hostname in groups['workers']

#
- name: Add Drive Devices into Drive Containers
  shell: |
    weka cluster drive add {{ cont_id }} {{ container.drives.devices }} --force
  register: add_data_devices
  when: inventory_hostname in groups['workers']
- debug: msg={{ add_data_devices }}
  when: print_debug == true and inventory_hostname in groups['workers']
  # weka cluster drive add {{ item }} /dev/vdb /dev/vdc --allow-format-non-wekafs-drives --force
  # --gateway 192.168.1.1
  # deletate also works
  # delegate_to: "{{ hostvars[groups['workers'][0]]['ansible_hostname'] }}"
  # delegate_facts: True

#
#- name: Delete partition table
#  shell: |
#    dd if=/dev/zero of=/dev/nvme0n1 bs=1k count=10000
#    dd if=/dev/zero of=/dev/nvme0n2 bs=1k count=10000
#    nvme format /dev/nvme0n1 -f
#    nvme format /dev/nvme0n2 -f
#  register: del_part_table
#  when: inventory_hostname in groups['workers']
#- debug: msg={{ del_part_table }}
#  when: print_debug == true and inventory_hostname in groups['workers']

#
- name: Assign Number of Cores into Each Compute/Drives/Frontends Containers
  shell: |
    weka cluster container cores {{ cont_id }} {{ container.total_cores }} --drives-dedicated-cores {{ container.drives.cores }} --frontend-dedicated-cores {{ container.frontend.cores }}
  register: assign_cores_num
  when: inventory_hostname in groups['workers']
- debug: msg={{ assign_cores_num  }}
  when: inventory_hostname in groups['workers'] and print_debug == true
  # deletate also works
  # delegate_to: "{{ hostvars[groups['workers'][0]]['ansible_hostname'] }}"
  # delegate_facts: True


#
- name: Dedicate Containers if Applicable
  shell: |
    weka cluster container dedicate {{ cont_id }} on
  register: dedicate_container
  when: inventory_hostname in groups['workers']
- debug: msg={{ dedicate_container }}
  when: inventory_hostname in groups['workers'] and print_debug == true
  # deletate also works
  # delegate_to: "{{ hostvars[groups['workers'][0]]['ansible_hostname'] }}"
  # delegate_facts: True


#
- name: Check drivers in the cluster
  shell: |
    weka cloud enable
  register: check_cluster_drives
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ check_cluster_drives }}
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname'] and print_debug == true
#    weka cluster node

#
- name: Created a Cluster Name
  shell: |
    weka cluster update --data-drives={{ container.drives.data }} --parity-drives={{ container.drives.parity }}
    weka cluster hot-spare {{ container.drives.hotspare }}
    weka cluster update --cluster-name={{ weka.cluster_name }}
  register: create_cluster_name
- debug: msg={{ create_cluster_name }}
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname'] and print_debug == true

#
- name: Apply changes of core numbers for containers
  shell: |
    weka cluster container apply --all --force
  register: apply_changes_core_num
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ apply_changes_core_num  }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Validate if Changes are still applying
  shell: weka status
  register: check_apply_status
  until: check_apply_status.stderr.find("Make sure weka is running on this host by running") == -1
  retries: 30
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ check_apply_status }}
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname'] and print_debug == true

#
- name: Start IO in the cluster
  shell: |
    weka cluster start-io
  register: start_cluster_io
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ start_cluster_io }}
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname'] and print_debug == true

#
- name: Copy expect script file to change admin password
  copy: src=change-admin-pass.sh dest=/root/change-admin-pass.sh mode=0755 owner=root group=root
  register: copy_expect_file
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ copy_expect_file }}
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname'] and print_debug == true

#
- name: Change admin password
  shell: /root/change-admin-pass.sh
  register: change_admin_pass
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ change_admin_pass }}
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname'] and print_debug == true

