---
- name: Get SSH Key Sscan
  shell: |
    ssh-keyscan -t rsa,dsa {{ ipaddr }} >> {{ _weka.base_path }}/.ssh/known_hosts
  register: ssh_key_scan
  ignore_errors: true
- debug: msg={{ ssh_key_scan }}
  when: print_debug == true


- name: Destroy Weka Software Binary
  shell: |
    {{ _weka.base_path }}/tools/install/wekadestroy -f -y -u {{ ipaddr }}
  register: destroy_weka_clu
  ignore_errors: true
- debug: msg={{ destroy_weka_clu }}
  when: print_debug == true


- name: Unmount tmpfs
  shell: |
    umount /opt/weka/data/agent/tmpfss/cross-container-rpc-the-tmpfs
  register: umount_tmpfs
  when: inventory_hostname in groups['control']
  ignore_errors: true
- debug: msg={{ umount_tmpfs }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Clear Memory Cache
  shell: |
    sync && echo 3 > /proc/sys/vm/drop_caches
  register: clear_cache_memory
  ignore_errors: true
- debug: msg={{ clear_cache_memory }}
  when: print_debug == true


#- name: Reboot required
#  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible updates triggered" ) &
#  async: 1200
#  poll: 0
#  when:  destroy_weka == true and inventory_hostname in groups['workers']
#  notify:
#    - Waiting for server to come back after reboot


#- meta: flush_handlers

