---
- name: Get SSH Key Sscan
  shell: |
    ssh-keyscan -t rsa,dsa {{ ipaddr }} >> {{ _weka.base_path }}/.ssh/known_hosts
  register: ssh_key_scan
  ignore_errors: true
- debug: msg={{ ssh_key_scan }}
  when: print_debug == true


- name: Copy Expect Script File to Stop IO Operation
  template: src=weka-stop-io.sh.j2 dest={{ _weka.base_path }}/weka-stop-io.sh owner=root group=root mode=755 force=yes
  when: inventory_hostname in groups['control']


- name: Stop Weka IO
  shell: |
    {{ _weka.base_path }}/weka-stop-io.sh
  ignore_errors: true
  environment:
    WEKA_USERNAME: "{{ _weka.admin_user }}"
    WEKA_PASSWORD: "{{ _weka.admin_default_pass }}"
  when: inventory_hostname in groups['control']


#[root@rk9-node05 ~]# sh force-destroy-mcb.sh
#error: Passed an unknown container name: default
#error: Passed an unknown container name: frontend0
#error: Passed an unknown container name: compute0
#error: Passed an unknown container name: drives0


#- name: Force Kill MCB Containers
#  shell: |
#    for i in `ps -ef | grep weka_init | grep -v grep | awk '{print $2}'`; do kill -9 $i ;done
#  register: kill_mcb_containers
#  with_sequence: start=0 end=10
#  ignore_errors: true
#- debug: msg={{ kill_mcb_containers }}
#when: print_debug == true


- name: Copy Force Destroy MCB Script
  template: src=force-destroy-mcb.sh.j2 dest={{ _weka.base_path }}/force-destroy-mcb.sh owner=root group=root mode=755 force=yes


- name: Force Destroy MCB
  shell: |
    {{ _weka.base_path }}/force-destroy-mcb.sh 2>&1 | wc -l
  register: force_destroy_mcb
  until: force_destroy_mcb.stdout|int == 3
  retries: 50
  delay: 10


- meta: end_play

# weka local stop {{ item }} && weka local disable {{ item }} && weka local rm -f {{ item }}
- name: Stop MCB Containers
  shell: |
    weka local stop {{ item }}
  register: stop_mcb_containers
  ignore_errors: true
  environment:
    WEKA_USERNAME: "{{ _weka.admin_user }}"
    WEKA_PASSWORD: "{{ _weka.admin_default_pass }}"
  with_items:
    - "{{ container.frontend.name }}"
    - "{{ container.compute.name }}"
    - "{{ container.drives.name }}"
- debug: msg={{ stop_mcb_containers }}
  when: print_debug == true
# - "{{ container.envoy.name }}"


- name: Disable MCB Containers
  shell: |
    weka local disable {{ item }}
  register: disable_mcb_containers
  ignore_errors: true
  environment:
    WEKA_USERNAME: "{{ _weka.admin_user }}"
    WEKA_PASSWORD: "{{ _weka.admin_default_pass }}"
  with_items:
    - "{{ container.frontend.name }}"
    - "{{ container.compute.name }}"
    - "{{ container.drives.name }}"
- debug: msg={{ disable_mcb_containers }}
  when: print_debug == true
# - "{{ container.envoy.name }}"


- name: Remove MCB Containers
  shell: |
    weka local rm -f {{ item }}
  register: remove_mcb_containers
  ignore_errors: true
  environment:
    WEKA_USERNAME: "{{ _weka.admin_user }}"
    WEKA_PASSWORD: "{{ _weka.admin_default_pass }}"
  with_items:
    - "{{ container.frontend.name }}"
    - "{{ container.compute.name }}"
    - "{{ container.drives.name }}"
- debug: msg={{ remove_mcb_containers }}
  when: print_debug == true
# - "{{ container.envoy.name }}"

