#
# - debug: msg={{ "Disable object store" }}

# $ weka s3 bucket create name jtest-bucket01 --policy public --policy-json
# Cannot pass option "policy-json" for command "weka s3 bucket create" without its value, please make sure to pass a value and check that the format is correct if a value was passed


# $ weka user login admin Changeme12\!\@
# +------------------------------+
# | Login completed successfully |
# +------------------------------+

# $ weka s3 bucket create jtest-bucket01 --policy public
# error: Internal error: core.exception.RangeError: Index/key not found
# in FileSystemRow[RawTypedIdentifier!("FSId", uint, 4294967295u, 4294967295u, FMT(""), false)] :
# FSId<4294967295>

# $ weka fs
# FILESYSTEM ID  FILESYSTEM NAME  USED SSD  AVAILABLE SSD  USED TOTAL  AVAILABLE TOTAL  THIN PROVISIONED  THIN PROVISIONED MINIMUM SSD  THIN PROVISIONED MAXIMUM SSD
# 0              jtest-fs01       20.47 KB  7.51 GB        20.47 KB    7.51 GB          False

# $ weka s3 bucket create jtest-bucket01 --policy public --fs-name jtest-fs01
# error: Could not find a running S3 container to run the command in

# $ weka s3 bucket create jtest-bucket01 --policy public --fs-name jtest-fs01 --fs-id 0
# error: Only one of fs-name or fs-id can be used

#
#- name:  Delete WekaFS attached into Object Store Tier
#  shell: |
#    weka fs delete jtest-obs-fs01 --force
#  register: update_obs_fs_grp
#  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
#- debug: msg={{ update_obs_fs_grp }}

#
- name:  Delete Object Store Tier
  shell: |
    weka fs tier s3 delete jtest-obs-tier01
  register: delete_obs_tier
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ delete_obs_tier }}

#
- name:  Delete Object Store
  shell: |
    weka fs tier obs delete jtest-obs01
  register: delete_obs
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ delete_obs }}

