

# $ weka s3 bucket create name jtest-bucket01 --policy public --policy-json
# Cannot pass option "policy-json" for command "weka s3 bucket create" without its value, please make sure to pass a value and check that the format is correct if a value was passed


# $ weka user login admin Changeme12\!\@
# +------------------------------+
# | Login completed successfully |
# +------------------------------+

# $ weka s3 bucket create jtest-bucket01 --policy public
# error: Internal error: core.exception.RangeError: Index/key not found
# in FileSystemRow[RawTypedIdentifier!("FSId", uint, 4294967295u, 4294967295u, FMT(""), false)] :
# FSId<4294967295>

# $ weka fs
# FILESYSTEM ID  FILESYSTEM NAME  USED SSD  AVAILABLE SSD  USED TOTAL  AVAILABLE TOTAL  THIN PROVISIONED  THIN PROVISIONED MINIMUM SSD  THIN PROVISIONED MAXIMUM SSD
# 0              jtest-fs01       20.47 KB  7.51 GB        20.47 KB    7.51 GB          False

# $ weka s3 bucket create jtest-bucket01 --policy public --fs-name jtest-fs01
# error: Could not find a running S3 container to run the command in

# $ weka s3 bucket create jtest-bucket01 --policy public --fs-name jtest-fs01 --fs-id 0
# error: Only one of fs-name or fs-id can be used


