# weka smb cluster create jtest-smb-clu01 jtest.pivotal.io --domain-netbios-name JTEST \
# --container-ids 0,1,2,3,4 --smb-ips-range 192.168.0.151-155 jtest-default-fs01


# weka smb cluster status

# weka local exec -C smbw

#
# On Freeipa
# ipa-adtrust-install --netbios-name JTEST -a changeme
#



# Setup: SMB service on WEKA
# Setting up an SMB cluster is a little simpler, assuming no floating IPs are required. You only need to select the hosts you wish to use, the Netbios name to create, and the domain name you’re looking to join - for this to work, you must be able to resolve DNS records for the AD service from the WEKA backends.
# weka smb cluster create wekasmb ad.example.com --container-ids 0,1,2

# Now wait for the SMB cluster service to be ready everywhere:
# weka smb cluster status
# HostId<0>: Ready

# And join using a priviliged AD account:
# weka smb domain join Administrator
# Password for Administrator:
# Using short domain name -- AD
# Joined 'WEKASMB' to dns domain 'ad.example.com'
# Not doing automatic DNS update in a clustered setup.

# Check that the ID mapping backend is “rfc2307”
# weka smb cluster

# And that the Active Directory has been joined
# weka smb domain
#   Domain Name:             ad.example.com
#   Domain Joined:           True
#   Domain Admin Username:   Administrator
#   Domain Netbios Name:     ad

# Optional, but useful: setting up DNS A records for either the SMB-running Backends or the Floating IPs allows you to access the SMB service by name (and also allows the use of the strongly-preferred later authentication algorithms).
# PS C:\Users\Administrator> Add-DnsServerResourceRecordA -Name "wekasmb" -ZoneName "ad.example.com" -AllowUpdateAny -IPv4Address "192.168.114.100"
# PS C:\Users\Administrator> Add-DnsServerResourceRecordA -Name "wekasmb" -ZoneName "ad.example.com" -AllowUpdateAny -IPv4Address "192.168.114.101"
# PS C:\Users\Administrator> Add-DnsServerResourceRecordA -Name "wekasmb" -ZoneName "ad.example.com" -AllowUpdateAny -IPv4Address "192.168.114.102"

# https://www.notion.so/wekaio/Multi-protocol-SMB-and-NFS-single-filesystem-access-8abcd9d23e004549a66e2e98fbcbd787?pvs=4
#


###################################################################################################################
# weka smb cluster destroy -f
# weka smb cluster create jtest-smb-clu01 jtest.weka.io --domain-netbios-name JTEST --container-ids 0,1,2,3,4 \
# --smb-ips-range 192.168.0.151-155 jtest-default-fs01

# weka smb cluster create wekasmb jtest.weka.io --container-ids 0,1,2,3,4 jtest-default-fs01

# weka smb domain join Administrator --debug --extra-options --domain-ou "jtest.weka.io"

# weka local exec --container smbw /usr/sbin/pcs cluster status

# weka local exec --container smbw cat /tmp/smbw-config-fs/.smbw/tsmb.conf

# weka smb cluster update
