---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'

#
- name: Set facts for Installing Weka Data Platform
  import_tasks: set-weka-install-facts.yml
  tags:
    - install
  when: inventory_hostname in groups['workers']

#
- name: Set facts for Uninstalling Weka Data Platform
  import_tasks: set-weka-uninstall-facts.yml
  tags:
    - uninstall
  when: inventory_hostname in groups['workers']

#
- name: Install Weka and tools binary
  import_tasks: setup-weka-binary.yml
  tags: install
  when: setup_weka_binary == true and inventory_hostname in groups['workers']

#
- name: Deploy Single Container Backend of Weka Data Platform v{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}{{ weka.patch_version }}
  import_tasks: deploy-scb.yml
  tags: install
  when: weka.backend.scb == true and inventory_hostname in groups['workers']

#
- name: Deploy Multi Container Backend of Weka Data Platform v{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}{{ weka.patch_version }}
  import_tasks: deploy-mcb-udp.yml
  tags: install
  when: weka.backend.mcb == true and weka.use_res_gen == false and inventory_hostname in groups['workers']

#
- name: Deploy Multi Container Backend of Weka Data Platform v{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}{{ weka.patch_version }}
  import_tasks: deploy-mcb-rg.yml
  tags: install
  when: weka.backend.mcb == true and weka.use_res_gen == true and inventory_hostname in groups['workers']

#
- name: Destroy Weka Data Platform Software v{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}{{ weka.patch_version }}
  import_tasks: uninstall.yml
  tags: uninstall
  when: inventory_hostname in groups['workers']

