---
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'
    - inventory_hostname in groups['workers']


- name: Set facts for Installing Weka Data Platform
  import_tasks: set-install-facts.yml
  tags: upload, deploy, install, setup, create, enable
  when: inventory_hostname in groups['workers']


- name: Set facts for Virtual Network Adapters Such as VMware or Public Clouds
  import_tasks: set-virt-net-facts.yml
  tags: upload, deploy, install, setup, create, enable
  when: _weka.backend.net.type == "virtual" and inventory_hostname in groups['workers']


- name: Set facts for Uninstalling Weka Data Platform
  import_tasks: set-uninstall-facts.yml
  tags: remove, destroy, uninstall, delete, disable, stop
  when: inventory_hostname in groups['workers']


- name: Create Addtional Swap Space
  import_tasks: ext/enable-ext-swap.yml
  tags: enable, install
  when: ( swap is defined and swap == true ) and inventory_hostname in groups['workers']


- name: Upload Weka Software Binary
  import_tasks: upload-weka-bin.yml
  tags: upload, install
  when: ( bin is defined and bin == true ) and inventory_hostname in groups['workers']


- name: Setup Weka Sofware and Tools Binary
  import_tasks: setup-weka-bin.yml
  tags: setup, install
  when: ( bin is defined and bin == true ) and inventory_hostname in groups['workers']


- name: Destroy Weka Default Containers
  import_tasks: remove-default-container.yml
  tags: remove, delete
  when: ( default is defined and default == true ) and inventory_hostname in groups['workers']


- name: Deploy Multi Container Backend of Weka Data Platform
  import_tasks: deploy-mcb.yml
  tags: deploy, install
  when: ( mcb is defined and mcb == true ) and inventory_hostname in groups['workers']


- name: Deploy Single Container Backend of Weka Data Platform
  import_tasks: deploy-scb.yml
  tags: deploy, install
  when: ( scb is defined and scb == true ) and inventory_hostname in groups['workers']


- name: Change Weka Admin Password
  import_tasks: change-admin-passwd.yml
  tags: change, install
  when: ( passwd is defined and passwd == true ) and inventory_hostname in groups['control']


- name: Destroy Weka MCB Cluster
  import_tasks: destroy-mcb.yml
  tags: destroy, uninstall
  when: (( mcb is defined and mcb == true ) and ( noc is defined and noc == true )) and inventory_hostname in groups['workers']


- name: Destroy Weka Instance
  import_tasks: destroy-weka-bin.yml
  tags: destroy, uninstall
  when: ( bin is defined and bin == true ) and inventory_hostname in groups['workers']


- name: Force Destroy Weka MCB Cluster
  import_tasks: ext/force-destroy-mcb.yml
  tags: destroy, uninstall
  when: (( mcb is defined and mcb == true ) and ( force is defined and force == true )) and inventory_hostname in groups['workers']


- name: Force Destroy Weka SCB Cluster
  import_tasks: ext/force-destroy-scb.yml
  tags: destroy, uninstall
  when: (( scb is defined and scb == true ) and ( force is defined and force == true )) and inventory_hostname in groups['workers']


- name: Disable Addtional Swap Space
  import_tasks: ext/disable-ext-swap.yml
  tags: disable, uninstall
  when: ( swap is defined and swap == true ) and inventory_hostname in groups['workers']


- name: Start Weka IO
  import_tasks: ext/start-weka-io.yml
  tags: start, uninstall
  when: ( io is defined and io == true ) and inventory_hostname in groups['control']


- name: Stop Weka IO
  import_tasks: ext/stop-weka-io.yml
  tags: stop, uninstall
  when: ( io is defined and io == true ) and inventory_hostname in groups['control']


- name: Cleanup NVME Block Devices
  import_tasks: ext/cleanup-nvme-devices.yml
  tags: clean
  when: ( nvme is defineed and nvme == true ) and inventory_hostname in groups['workers']

