---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'

#
- name: Deploy Weka Data Platform v{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}.{{ weka.patch_version }}
  import_tasks: install.yml
  tags: install
  when: deploy_weka == true

#
- name: Config Client
  import_tasks: config-client.yml
  tags: install
  when: config_client == true

#
- name: Create Weka File System
  import_tasks: create-wekafs.yml
  tags: install
  when: create_wekafs == true

#
- name: Uninstall Weka
  import_tasks: uninstall.yml
  tags: uninstall
  when: destroy_weka == true

