---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'
    - inventory_hostname in groups['workers']


- name: Set facts for Installing Weka Data Platform
  import_tasks: set-install-facts.yml
  tags:
    - upload
    - install
  when: inventory_hostname in groups['workers']


- name: Set facts for Virtual Network Adapters Such as VMware or Public Clouds
  import_tasks: set-virt-net-facts.yml
  tags: install
  when: weka.backend.net.type == "virtual" and inventory_hostname in groups['workers']


- name: Set facts for Uninstalling Weka Data Platform
  import_tasks: set-uninstall-facts.yml
  tags: uninstall
  when: inventory_hostname in groups['workers']


- name: Upload Weka Software Binary
  import_tasks: upload-weka-bin.yml
  tags: upload
  when: inventory_hostname in groups['workers']


- name: Setup Weka Sofware and Tools Binary
  import_tasks: setup-weka-bin.yml
  tags: install
  when: setup_weka_bin == true and inventory_hostname in groups['workers']


- name: Deploy Single Container Backend of Weka Data Platform v{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}{{ weka.patch_version }}
  import_tasks: deploy-scb.yml
  tags: install
  when: weka.backend.scb == true and inventory_hostname in groups['workers']


- name: Deploy Multi Container Backend of Weka Data Platform v{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}{{ weka.patch_version }} on Virtualization Environment
  import_tasks: deploy-mcb.yml
  tags: install
  when: weka.backend.mcb == true and inventory_hostname in groups['workers']


- name: Destroy Weka Data Platform Software v{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}{{ weka.patch_version }}
  import_tasks: uninstall.yml
  tags: uninstall
  when: inventory_hostname in groups['workers']

