---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'

#
- name: Set facts for Weka Data Platform
  import_tasks: set-weka-facts.yml
  tags:
    - install
    - uninstall

#
- name: Install Weka and tools binary
  import_tasks: install-binary.yml
  tags: install
  when: install_binary == true

#
- name: Deploy Weka Data Platform v{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}.{{ weka.patch_version }}
  import_tasks: deploy-weka.yml
  tags: install
  when: deploy_weka == true

#
- name: Create Weka File System
  import_tasks: create-wekafs.yml
  tags: install
  when: create_wekafs == true

#
- name: Config Client
  import_tasks: config-client.yml
  tags: install
  when: config_client == true

#
- name: Delete Weka File System
  import_tasks: delete-wekafs.yml
  tags: uninstall
  when: delete_wekafs == true

#
- name: Unconfig Client
  import_tasks: unconfig-client.yml
  tags: uninstall
  when: unconfig_client == true

#
- name: Destroy Weka Data Platform Software
  import_tasks: uninstall.yml
  tags: uninstall

#
- name: Enable Object Storage Tier
  import_tasks: enable-obs.yml
  tags: install
  when: enable_obs == true

#
- name: Disable S3 Object Storage Tier
  import_tasks: disable-obs.yml
  tags: uninstall
  when: disable_obs == true

