---
#
- name: Get interface name from provided IP
  set_fact:
    netdev0: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', weka.net.ipaddr0 ) | map(attribute='device') | first }}"
#- debug: msg={{ netdev0 }}

#
- name: Get IP Address from provided network device name
  set_fact:
    ipaddr0: "{{ hostvars[inventory_hostname]['ansible_'~netdev0].ipv4.address }}"
#- debug: msg: {{ ipaddr0 }}

# https://stackoverflow.com/questions/36328907/ansible-get-all-the-ip-addresses-of-a-group
- name: Define facts for all worker's hostname
  set_fact:
    all_ext1_hostnames: "{{ groups['workers'] | map('extract', hostvars, ['ansible_hostname']) | join(' ') }}"
#- debug: msg={{ all_ext1_hostnames }}

#
- name: Define fact for all addresses of each network devices
  set_fact:
    all_ext1_ipaddrs: "{{ groups['workers'] | map('extract', hostvars, ['ansible_'~netdev0, 'ipv4', 'address']) | join(',') }}"
- debug: msg={{ all_ext1_ipaddrs }}

#
- name: Define fact for Weka version
  set_fact:
    weka_file_name: "weka-{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}{{ weka.patch_version }}"
- debug: msg={{ weka_file_name }}

#
- name: Define fact for Weka tools version
  set_fact:
    weka_tools_file_name: "{{ weka.tools.name }}-v{{ weka.tools.major_version }}.{{ weka.tools.minor_version }}.{{ weka.tools.patch_version }}"
- debug: msg={{ weka_tools_file_name }}


################################################################################################################################################
#
#- name: Set Facts of Drives Container Net into all hosts
#  set_fact:
#    drives_net: "--net {{ netdev1 }}/{{ ipaddr1 }}/24 --net {{ netdev2 }}/{{ ipaddr2 }}/24"
#  delegate_facts: True
#  when: weka.net.conn == "dpdk" and inventory_hostname in groups['workers']
#
##
#- name: Set Facts of Drives Container Net into all hosts
#  set_fact:
#    drives_net: ""
#  delegate_facts: True
#  when: weka.net.conn != "dpdk" and inventory_hostname in groups['workers']
#
##
#- name: Set Facts of Compute Container Net into all hosts
#  set_fact:
#    compute_net: "--net {{ netdev3 }}/{{ ipaddr3 }}/24"
#  delegate_facts: True
#  when: weka.net.conn == "dpdk" and inventory_hostname in groups['workers']
#
##
#- name: Set Facts of Compute Container Net into all hosts
#  set_fact:
#    compute_net: ""
#  delegate_facts: True
#  when: weka.net.conn != "dpdk" and inventory_hostname in groups['workers']
#
##
#- name: Set Facts of Frontend Container Net into all hosts
#  set_fact:
#    frontend_net: "--net {{ netdev4 }}/{{ ipaddr4 }}/24"
#  delegate_facts: True
#  when: weka.net.conn == "dpdk" and inventory_hostname in groups['workers']
#
##
#- name: Set Facts of Frontend Container Net into all hosts
#  set_fact:
#    frontend_net: ""
#  delegate_facts: True
#  when: weka.net.conn != "dpdk" and inventory_hostname in groups['workers']

