# find /sys/class/net -type l -not -lname '*virtual*' -printf '%f\n' | sort
- name: Set Facts for Network Devices, Sequence and Prefix after Finding All Network Devices Except lo
  set_fact:
    netseq: "{{ ansible_facts.interfaces | reject( 'search', 'lo' ) | map( 'regex_search' , '[0-9]*$' ) | sort }}"
    netdevs: "{{ ansible_facts.interfaces | reject( 'search', 'lo' ) | sort }}"
    netfix: "{{ ansible_facts.interfaces | reject( 'search', 'lo' ) | map( 'regex_search' , '^[a-zA-Z][a-zA-Z][a-zA-Z]' ) | sort | first }}"
    netcnt: "{{ ansible_facts.interfaces | reject( 'search', 'lo' ) | map( 'regex_search' , '[0-9]*$' ) | sort | count|int - 1 }}"


- name: Set Facts for Number of Total Cores and Virtual Network Adapters
  set_fact:
    tcores: "{{ container.drives.cores|int + container.compute.cores|int + container.frontend.cores|int }}"


- name: Check if the Number of Virtual Network Adapters is Larger Than Number of Cores to Assign into All Containers"
  fail: msg="The Number of Virtual Network Adapters Should Be larger than Number of Cores to Assign into All Containers"
  when: tcores|int > netcnt|int


- set_fact:
    netdev_seq: "{{ dict( range(0,netcnt|int+1) | zip(netseq)) | dict2items(key_name='seq', value_name='end_seq') }}"
- debug: msg={{ netdev_seq }}
  when: print_debug == true


- name: Define Variables for Network Device Names and IP Addresses and All Network Addresses Provided by IP Addresses and Prefix of Netdev
  set_fact:
    "{{ 'ipaddr'~item.seq }}": "{{ hostvars[inventory_hostname]['ansible_'~ netfix ~ item.end_seq ].ipv4.address }}"
    "{{ 'all_net'~item.seq~'_ipaddrs' }}": "{{ groups['workers'] | map('extract', hostvars, ['ansible_' ~ netfix ~ item.end_seq, 'ipv4', 'address']) | join(',') }}"
    "{{ 'netdev'~item.seq }}": "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _weka.backend.net['ipaddr'~item.seq] ) | map(attribute='device') | first }}"
  with_items: "{{ netdev_seq }}"


- name: Define Facts for All Hostnames and Management IP Addresses
  set_fact:
    all_ext1_hostnames: "{{ groups['workers'] | map('extract', hostvars, ['ansible_hostname']) | join(' ') }}"
    _all_mgmt_ipaddrs: "{{ groups['workers'] | map('extract', hostvars, ['ansible_'~ netdev5, 'ipv4', 'address']) | join(' ') }}"
    all_mgmt_ipaddrs: "{{ groups['workers'] | map('extract', hostvars, ['ansible_'~ netdev5, 'ipv4', 'address']) | join(',') }}"
    mgmt_ipaddr: "{{ ipaddr5 }}"
    # all_management_ipaddrs: "{{ groups['workers'] | map('extract', hostvars, ['ansible_'~ netdev5, 'ipv4', 'address']) | join(' ') }}"


#- debug: msg={{ ['netdev'~item.seq] }}
#  with_items: "{{ netdev_seq }}"
#- debug: msg={{ ['ipaddr'~item.seq] }}
#  with_items: "{{ netdev_seq }}"

- debug: msg={{ netdev0 }}
- debug: msg={{ netdev1 }}
- debug: msg={{ netdev5 }}

- debug: msg={{ ipaddr0 }}
- debug: msg={{ ipaddr1 }}
- debug: msg={{ ipaddr5 }}


# - debug: msg={{ all_ext1_hostnames }}
- debug: msg={{ "all_mgmt_ipaddrs" }}
- debug: msg={{ all_mgmt_ipaddrs }}
- debug: msg={{ "mgmt_ipaddr" }}
- debug: msg={{ mgmt_ipaddr }}

# - meta: end_play


# Examle
#- name: Set HA Fact to Merge IP Addresses
#  set_fact:
#    ha_ips: {% for h in groups['workers'] %}{{hostvars[h]['ansible_' ~ netfix ~ _weka.net.ha1]['ipv4']['address']}}+{{ hostvars[h]['ansible_' ~ netfix ~ _weka.net.ha2]['ipv4']['address'])}}{% if not loop.last %},{% endif %}{% endfor %}

# Example of define variables repeatedly with with_items
#- name: Set individual facts for individual HA IPs
#  set_fact:
#    "{{ 'ha_ips'~item }}": "{{ ipaddr1 }}+{{ ipaddr2 }}"
#  with_items: "{{ netseq }}"


# _weka.net['ipaddr'~item] ) | map(attribute='device') | first }}"
- name: Set Facts for HA IP Addresses of Individual Hosts
  set_fact:
    ha_ips0: "{{ vars['ipaddr'~_weka.net.ha1] }}+{{ vars['ipaddr'~_weka.net.ha2] }}"
- debug: msg={{ ha_ips0 }}
  when: print_debug == true


- name: Set Facts for HA IP Addresses of All Hosts
  set_fact:
    ha_ips: "{{ groups['workers'] | map('extract', hostvars, ['ha_ips0']) | join(',') }}"
- debug: msg={{ ha_ips }}
  when: print_debug == true


# _weka.net['ipaddr'~item] ) | map(attribute='device') | first }}"
- name: Set Facts for HA Join IP Addresses of Individual Hosts
  set_fact:
    ha_join_ips0: "{{ vars['ipaddr'~_weka.net.ha1] }},{{ vars['ipaddr'~_weka.net.ha2] }}"
- debug: msg={{ ha_join_ips0 }}
  when: print_debug == true


- name: Set Facts for HA Join IP Addresses of All Hosts
  set_fact:
    ha_join_ips: "{{ groups['workers'] | map('extract', hostvars, ['ha_join_ips0']) | join(',') }}"
- debug: msg={{ ha_join_ips }}
  when: print_debug == true


# Example of variable appended with_items
#- debug:
#    msg: "{{ vars['ha_ips'~item] }}"
#  with_items: "{{ netseq }}"
#
# Example of cut last a character in a line
# ha_ips: "{{ ha_ips0[:-1] }}"


- name: Define Fact for Weka Version
  set_fact:
    weka_file_name: "weka-{{ _weka.major_version }}.{{ _weka.minor_version }}.{{ _weka.build_version }}{{ _weka.patch_version }}"
    weka_tools_file_name: "{{ _weka.tools.name }}-v{{ _weka.tools.major_version }}.{{ _weka.tools.minor_version }}.{{ _weka.tools.patch_version }}"


- name: Set Facts of Drives Container Net into all Hosts
  set_fact:
    drives_net: ""
    compute_net: ""
    frontend_net: ""
  delegate_facts: True
  when: _weka.net.conn != "dpdk"


#- set_fact: # Set Fact to Split IP Addresses
#    even: "{{ groups['workers'][::2] }}"
#    odd: "{{ groups['workers'][1::2] }}"


- debug:
    msg: "{{ vars['all_net'~item~'_ipaddrs'].split(',')[0] }}"
  with_items:
    - "{{ _weka.net.ha1 }}"
    - "{{ _weka.net.ha2 }}"


- name: Check if the Rest Value Exists
  set_fact:
    rest: "{{ _weka.host_num|int % 2 }}"
- debug: msg={{ rest }}
  when: print_debug == true


- name: Set Number Divided in Case that Rest Value is Not Equals to 0
  set_fact:
    llen: "{{ ( _weka.host_num|int / 2 ) | int }}"
  when: ( rest|int == 0 )


- name: Set number divided in case that rest value not equals to 0
  set_fact:
    llen: "{{ ( _weka.host_num|int / 2 - 0.5 ) | int }}"
  when: ( rest|int != 0 )


- name: Set Facts for left numbers divded in case that rest value not equals to 0
  set_fact:
    rlen: "{{ ( _weka.host_num|int - llen|int ) | int }}"


- name: Set Facts for right numbers divded in case that rest value not equals to 0
  debug:
    msg: "{{ llen }} {{ rlen }}"


#- name: Define Variables for Network Device Names and IP Addresses and All Network Addresses Provided by IP Addresses and Prefix of Netdev
#  set_fact:
#    all_ha1_ipaddrs: "{{ groups['workers'] | map('extract', hostvars, ['ansible_'~ netfix ~ _weka.net.ha1, 'ipv4', 'address']) | join(',') }}"
#    all_ha2_ipaddrs: "{{ groups['workers'] | map('extract', hostvars, ['ansible_'~ netfix ~ _weka.net.ha2, 'ipv4', 'address']) | join(',') }}"
#  when: netfix == "eth"


- name: Define Variables for Network Device Names and IP Addresses and All Network Addresses Provided by IP Addresses and Prefix of Netdev
  set_fact:
    all_ha1_ipaddrs: "{{ groups['workers'] | map('extract', hostvars, ['ansible_'~ netfix ~ netseq.1, 'ipv4', 'address']) | join(',') }}"
    all_ha2_ipaddrs: "{{ groups['workers'] | map('extract', hostvars, ['ansible_'~ netfix ~ netseq.2, 'ipv4', 'address']) | join(',') }}"


# Examples
# msg: "{{ dict( [ all_net1_ipaddrs.split(',') | list ] | slice(2) ) }}"
- name: Convert strings seperated with comma to list
  set_fact:
    list_all_ha1: "{{ all_ha1_ipaddrs.split(',') | list }}"
    list_all_ha2: "{{ all_ha2_ipaddrs.split(',') | list }}"


#- debug: msg={{ list_all_ha1[0:llen|int] }}
#  when: print_debug == true
#- debug: msg={{ list_all_ha1[llen|int:_weka.host_num|int] }}
#  when: print_debug == true
#- debug: msg={{ list_all_ha2[0:llen|int] }}
#  when: print_debug == true
#- debug: msg={{ list_all_ha2[llen|int:_weka.host_num|int] }}
#  when: print_debug == true


- name: Split HA IP Addresses from two network interfaces
  set_fact:
    ha1_left: "{{ list_all_ha1[0:llen|int] }}"
    ha1_right: "{{ list_all_ha1[llen|int:_weka.host_num|int] }}"
    ha2_left: "{{ list_all_ha2[0:llen|int] }}"
    ha2_right: "{{ list_all_ha2[llen|int:_weka.host_num|int] }}"

#- debug: msg={{ ha1_left }}
#  when: print_debug == true
#- debug: msg={{ ha1_right }}
#  when: print_debug == true
#- debug: msg={{ ha2_left }}
#  when: print_debug == true
#- debug: msg={{ ha2_right }}
#  when: print_debug == true


# Combine two list
- name: Paste HA IP Addresses splitted from two network interfaces
  set_fact:
    ha1_ips: "{{ [ ha1_left + ha2_right ] | flatten | join(',') }}"
    ha2_ips: "{{ [ ha2_left + ha1_right ] | flatten | join(',') }}"

#- debug: msg={{ ha1_ips }}
#  when: print_debug == true
#- debug: msg={{ ha2_ips }}
#  when: print_debug == true

# 목록에서 사전 만들기
# 대부분의 언어에서는 쌍 목록에서 사전(맵/연관 배열/해시 등)을 만드는 것이 쉽습니다. Ansible 에는 이를 수행하는 몇 가지 방법이 있으며 가장 적합한 방법은 소스에 따라 달라질 수 있습니다. 당신의 데이터.
# 이 예에서는 {"a": "b", "c": "d"} 를 생성합니다.
#
# 목록이 [key, value, key, value, …]라고 가정하여 구술하는 간단한 목록입니다.
# vars:
#     single_list: [ 'a', 'b', 'c', 'd' ]
#     mydict: "{{ dict(single_list | slice(2)) }}"
# 쌍 목록이 있으면 더 간단합니다.
# vars:
#     list_of_pairs: [ ['a', 'b'], ['c', 'd'] ]
#     mydict: "{{ dict(list_of_pairs) }}"

# Reference
# https://stackoverflow.com/questions/57596946/ansible-looping-over-with-items-n-times
# https://docs.ansible.com/ansible/latest/playbook_guide/complex_data_manipulation.html
# https://stackoverflow.com/questions/43281212/ansible-include-with-array-slices

#############################################################################################################################################################
# Network IP Address Combination when two network interfaces is applied
#############################################################################################################################################################
# 5 : 2 + 2 - 3 + 2, 0
# 6 : 3 + 3 - 3 + 2, 1
# 7 : 3 + 4 - 4 + 2, 1
#
#############################################################################################################################################################
# SSD net storage capacity calculation
#############################################################################################################################################################
# SSD Net Capacity
# = SSD Raw Capacity * ( ( # Failure Domain - Hot Spares )/ # Failure Domain ) * ( Stripe Width + Protection / Stripe Width ) ) * ( 1 - Filesystem Overhead )
#
#############################################################################################################################################################
# Scenario 1: A homogeneous system of 10 servers, each with one terabyte of Raw SSD Capacity, one hot spare, and a protection scheme of 6+2.
#############################################################################################################################################################
# SSDNetCapacity = 10TB * ( 10 - 1 )/10*6(6+2) * 0.9 = 6.075 TB
#
#############################################################################################################################################################
# Scenario 2: A homogeneous system of 20 servers, each with one terabyte of Raw SSD Capacity, two hot spares, and a protection scheme of 16+2.
#############################################################################################################################################################
# SSDNetCapacity = 20TB * (20-2)/20*16/(16+2)*0.9 = 14.4 TB
#
#############################################################################################################################################################

- name: Get NVME Devices List
  shell: |
    nvme list | sed 1,2d | awk '{print $1}' | paste -sd "," -
  register: nvme_device_list0
  when: _weka.nvme == true
- debug: msg={{ nvme_device_list0.stdout_lines }}
  when: print_debug == true and _weka.nvme == true


- set_fact:
    nvme_device_list: "{{ nvme_device_list0.stdout }}"
  when: _weka.nvme == true
- debug: msg={{ nvme_device_list }}
  when: print_debug == true and _weka.nvme == true


- name: Get NVME Devices Array
  shell: |
    nvme list | sed 1,2d | awk '{print $1}'
  register: nvme_device_array0
  when: _weka.nvme == true
- debug: msg={{ nvme_device_array0.stdout_lines }}
  when: print_debug == true and _weka.nvme == true


- set_fact:
    nvme_device_array: "{{ nvme_device_array0.stdout_lines }}"
  when: _weka.nvme == true
- debug: msg={{ nvme_device_array }}
  when: print_debug == true and _weka.nvme == true

