# Need to run wekachecker
# /root/tools/install/wekachecker 192.168.0.{171..175}

- name: Setup Weka Software Binary
  shell: |
    cd {{ _weka.base_path }}/{{ weka_file_name }} ; ./install.sh
  register: install_weka_binary
- debug: msg={{ install_weka_binary }}
  when: print_debug == true and inventory_hostname in groups['workers']


- name: Copy Sysctl for Weka
  template: src=98-weka-sysctl.conf.j2 dest=/etc/sysctl.d/98-weka-sysctl.conf mode=0644 owner=root group=root
  register: copy_sysctl_conf
  notify:
    - Reload Sysctl
- debug: msg={{ copy_sysctl_conf }}
  when: print_debug == true

