#
- name: Delete text file with the content
  shell: |
    rm -f {{ wekafs.mount_dir }}/test01.txt
  register: delete_wekafs_file
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ delete_wekafs_file }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Check if WekaFS directory is mounted
  shell: |
    df -h
    ls -al {{ wekafs.mount_dir }}
  register: check_wekafs_mounted
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ check_wekafs_mounted  }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Unmount WekaFS directory
  shell: |
    umount {{ wekafs.mount_dir }}
  register: unmount_wekafs_dir
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ unmount_wekafs_dir }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Delete directory to mount WekaFS
  shell: |
    rm -rf {{ wekafs.mount_dir }}
  register: delete_wekafs_dir
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']
- debug: msg={{ delete_wekafs_dir }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Destroy Weka Client
  shell: |
    cd /root/tools/install ; ./wekadestroy --yes --force --uninstall {{ hostvars[groups['clients'][0]]['ansible_hostname'] }}
  register: destroy_weka_client
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ destroy_weka_client }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
#- name: Uninstall WekaFS Client
#  shell: |
#    curl {{ hostvars[groups['workers'][0]]['ansible_eth0']['ipv4']['address'] }}:14000/dist/v1/install | sh
#  register: uninstall_wekafs_client
#  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']
#- debug: msg={{ uninstall_wekafs_client }}
