#

- name: Check the status of Weka cluster
  shell: |
    weka user login {{ weka.admin_user }} {{ weka.admin_default_pass }} && weka status
  register: check_weka_cluster
  ignore_errors: true
  when: inventory_hostname in groups['workers']

- debug: msg={{ check_weka_cluster }}
  when: print_debug == true and inventory_hostname in groups['workers']

#
# https://stackoverflow.com/questions/36328907/ansible-get-all-the-ip-addresses-of-a-group
- set_fact:
    all_nodes_hostname: "{{ groups['workers'] | map('extract', hostvars, ['ansible_hostname']) | join(' ') }}"

- debug: msg={{ all_nodes_hostname }}

#
- name: Destroy Weka Cluster
  shell: |
    cd /root/tools/install ; ./wekadestroy --yes --force --uninstall {{ all_nodes_hostname }}
  register: destroy_weka_cluster
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

- debug: msg={{ check_weka_cluster }}
  when: print_debug == true and  inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Reboot required
  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible updates triggered" ) &
  async: 1200
  poll: 0
  when: print_debug == true and inventory_hostname in groups['workers'] and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" )
  notify:
    - Waiting for server to come back after reboot

- meta: flush_handlers
  when: print_debug == true and inventory_hostname in groups['workers']
