---
- name: Check if Weka Tarball File Already Exists
  stat: path={{ _weka.base_path }}/{{ weka_file_name }}.{{ _weka.bin_type }}
  register: weka_tarball_exists
- debug: msg={{ weka_tarball_exists }}


- name: Check if Weka Installation Directory Already Exists
  stat: path={{ _weka.base_path }}/{{ weka_file_name }}
  register: weka_install_dir_exists


- name: Sanity Check for Existence of "{{ _weka.base_path }}/{{ weka_file_name }}".tar File or "{{ _weka.base_path }}/{{ weka_file_name }}" Directory
  debug: msg="Both {{ _weka.base_path }}/{{ weka_file_name }}.tar File and {{ _weka.base_path }}/{{ weka_file_name }} Directory already Exists"
  changed_when: weka_tarball_exists.stat.exists == True and weka_install_dir_exists.stat.exists == True


- name: Copy Weka Tarball from Local Directory, roles/weka/files
  copy: src={{ weka_file_name }}.tar dest={{ _weka.base_path }}/{{ weka_file_name }}.tar mode=0644 owner=root group=root
  register: local_copy_weka
  when: _weka.download == false and weka_tarball_exists.stat.exists != True


- name: Download Weka Tarball File
  shell: |
    wget -P {{ _weka.base_path }} --show-progress --auth-no-challenge https://CHANGEME_WEKA_TOKEN:@{{ weka.download_url }}/{{ weka_file_name }}.tar
  register: download_weka_tarball
  when: _weka.download == true and weka_tarball_exists.stat.exists == false


# https://xxxxxxxxxxxxxxxx:@get.weka.io/dist/v1/pkg/{{ weka_file_name }}.tar
#- name: Download weka tarball file
#  get_url:
#    url: "{{ server_url }}"
#    dest: "{{ _weka.base_path }}/{{ weka_file_name }}.tar"
#    owner: root
#    group: root
#    mode: 0755
#  when: _weka.download == true and weka_tarball_exists.stat.exists == false


- name: Unarchive Weka Tarball
  unarchive:
    src: "{{ _weka.base_path }}/{{ weka_file_name }}.{{ _weka.bin_type }}"
    dest: "{{ _weka.base_path }}"
    #  /{{ weka_file_name }}"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: yes
  register: unarchive_weka_tarball
  when: weka_install_dir_exists.stat.exists == false


# Start for Weka Tools
- name: Check if Weka Tools Directory Already Exists
  stat: path={{ _weka.base_path }}/{{ _weka.tools.name }}
  register: weka_tools_dir_exists


- name: Check if Weka Tools Tarball File Already Exists
  stat: path={{ _weka.base_path }}/{{ weka_tools_file_name}}.{{ _weka.tools.bin_type }}
  register: weka_tools_tarball_exists
- debug: msg={{ weka_tools_tarball_exists }}


- name: Sanity Check for Existence of "{{ _weka.base_path }}/{{ weka_tools_file_name }}.{{ _weka.tools.bin_type }}" File or "{{ _weka.base_path }}/{{ _weka.tools.name }}" Directory
  debug: msg="Both {{ _weka.base_path }}/{{ weka_tools_file_name }}.{{ _weka.tools.bin_type }} File and {{ _weka.base_path }}/{{ _weka.tools.name }} Directory Already Exists"
  changed_when: weka_tools_tarball_exists.stat.exists == True and weka_tools_dir_exists.stat.exists == True


- name: Copy Weka Tools Tarball File from Local Directory, roles/weka/files
  copy: src={{ weka_tools_file_name }}.{{ _weka.tools.bin_type }} dest={{ _weka.base_path }}/{{ weka_tools_file_name }}.{{ _weka.tools.bin_type }} mode=0644 owner=root group=root
  register: local_copy_weka_tools
  when: _weka.tools.download == false and weka_tools_dir_exists.stat.exists == false


#- name: Download Weka Tools Zip File from Github
#  get_url:
#    url: "{{ server_url }}"  # github url
#    dest: "{{ _weka.base_path }}/{{ weka_tools_file_name }}.zip"
#    owner: root
#    group: root
#    mode: 0755
#  when: _weka.tools.download == true and weka_tarball_exists.stat.exists == false


- name: Unarchive Weka Tools Tarball File
  unarchive:
    src: "{{ _weka.base_path }}/{{ weka_tools_file_name }}.{{ _weka.tools.bin_type }}"
    dest: "{{ _weka.base_path }}/"
    #  {{ _weka.tools.name }}"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: yes
  register: unarchive_weka_tools_tarball
  when: _weka.tools.download == false and weka_tools_dir_exists.stat.exists == false


- name: Create Symbolic Link for Weka Tools Directory
  file:
   src: "{{ _weka.base_path }}/{{ weka_tools_file_name }}"
   dest: "{{ _weka.base_path }}/{{ _weka.tools.name }}"
   state: link
   force: true


#- name: Check if Weka tools directory is already existed
#  stat: path={{ _weka.base_path }}/{{ _weka.tools.name }}
#  register: weka_tools_dir_exists2


#- name: Rename Weka tools directory
#  shell: mv {{ _weka.base_path }}/{{ weka_tools_file_name }} {{ _weka.base_path }}/{{ _weka.tools.name }}
#  register: rename_weka_tools_dir
#  when: _weka.tools.download == false and weka_tools_dir_exists2.stat.exists == false


- name: Clone Weka Tools from Github
  git:
    repo: https://github.com/weka/tools
    dest: /tmp/{{ _weka.tools.name }}
    force: yes
    clone: yes
  when: _weka.tools.download == false and weka_tools_dir_exists.stat.exists == false

