temp:
	@if [ "${r}" = "init" ] || [ "${r}" = "uninit" ] || [ "${r}" = "reinit" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to init/uninit/reinit temp";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{temp_all: True}' --tags='${r}';\
			else\
				echo "No actions to init/uninit/reinit temp";\
			fi\
		else\
			echo "No actions to init/uninit/reinit temp";\
		fi;\
	elif [ "${r}" = "upload" ] || [ "${r}" = "download" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to upload/download temp";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{temp_all: True}' --tags='${r}';\
			else\
				echo "No actions to upload/download temp";\
			fi\
		else\
			echo "No actions to upload/download temp";\
		fi;\
	elif [ "${r}" = "prepare" ] || [ "${r}" = "clean" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to prepare/clean temp";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{temp_all: True}' --tags='${r}';\
			else\
				echo "No actions to prepare/clean temp";\
			fi\
		else\
			echo "No actions to prepare/clean temp";\
		fi;\
	elif [ "${r}" = "enable" ] || [ "${r}" = "disable" ] || [ "${r}" = "start" ] || [ "${r}" = "stop" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to ennable/disable/start/stop temp";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{temp_all: True}' --tags='${r}';\
			else\
				echo "No actions to ennable/disable/start/stop temp";\
			fi\
		else\
			echo "No actions to ennable/disable/start/stop temp";\
		fi;\
	elif [ "${r}" = "deploy" ] || [ "${r}" = "destroy" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' -e '{"noc": true}' --tags='${r}';\
			elif [ ! -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' -e '{"${c}": True}' --tags='${r}';\
			else\
				echo "No actions to deploy/destroy temp";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{temp_all: True}' --tags='${r}';\
			else\
				echo "No actions to deploy/destroy temp";\
			fi\
		else\
			echo "No actions to deploy/destroy temp";\
		fi;\
	elif [ "${r}" = "create" ] || [ "${r}" = "delete" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to create/delete temp";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{temp_all: True}' --tags='${r}';\
			else\
				echo "No actions to create/delete temp";\
			fi\
		else\
			echo "No actions to create/delete temp";\
		fi;\
	elif [ "${r}" = "install" ] || [ "${r}" = "uninstall" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to install/uninstall temp";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{temp_all: True}' --tags='${r}';\
			else\
				echo "No actions to install/uninstall temp";\
			fi\
		else\
			echo "No actions to install/uninstall temp";\
		fi;\
	elif [ "${r}" = "add" ] || [ "${r}" = "setup" ] || [ "${r}" = "change" ] || [ "${r}" = "remove" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to add/setup/change/remove temp";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{temp_all: True}' --tags='${r}';\
			else\
				echo "No actions to add/setup/change/remove temp";\
			fi\
		else\
			echo "No actions to add/setup/change/remove temp";\
		fi;\
	elif [ "${r}" = "upgrade" ] || [ "${r}" = "downgrade" ]; then\
		if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{"${s}": True}' --tags='${r}';\
			else\
				echo "No actions to upgrade/downgrade temp";\
			fi\
		elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
			if [ -z ${c} ];  then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-temp.yml -e '{temp_all: True}' --tags='${r}';\
			else\
				echo "No actions to upgrade/downgrade temp";\
			fi\
		else\
			echo "No actions to upgrade/downgrade temp";\
		fi;\
	else\
		echo "No actions to temp role";\
		exit;\
	fi

