---
- name: Check OS ( Weka S3 )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'


- name: Set Facts for Installing Weka Data Platform
  import_tasks: set-s3-facts.yml
  tags: create, setup, install
  when: ( client is defined and client == true ) and ( inventory_hostname in groups['clients'] or inventory_hostname in groups['control'] )


- name: Deploy S3 Backends
  import_tasks: deploy-s3-backend.yml
  tags: deploy, setup, install
  when: ( backend is defined and backend == true ) and inventory_hostname in groups['control']


- name: Setup S3 Clients
  import_tasks: setup-s3-clients.yml
  tags: setup, create, install
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']


- name: Remove S3 Clients
  import_tasks: remove-s3-clients.yml
  tags: remove, delete, uninstall
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']


- name: Destroy S3 Backends
  import_tasks: destroy-s3-backend.yml
  tags: destroy, remove, uninstall
  when: ( backend is defined and backend == true ) and inventory_hostname in groups['control']

