#######################################################################################################################################
# Example
#######################################################################################################################################
# s3cmd del s3://BUCKET/OBJECT
# s3cmd del -r s3://BUCKET/FOLDER
# s3cmd ls s3://BucketName/foldername_prefix* |awk '{print $2}' | while read files; do s3cmd  rm -r $files; done
# s3cmd rm s3://mybucket/myfileidontwant --force
#

- name: Delete Parquet Test Files in S3 Backends
  shell: |
    s3cmd --no-check-certificate --config={{ _weka.base_path }}/s3cmd/{{ item.name }}-s3cfg del -r s3://{{ item.bucket }}/*.gz.parquet
  register: del_parq_files_s3
  async: 600
  poll: 0
  with_items: "{{ _s3.users }}"
- debug: msg={{ del_parq_files_s3 }}
  when: print_debug == true


- name: List Parquet Test Files Deleted
  shell: |
    s3cmd --no-check-certificate --config={{ _s3.base_path }}/s3cmd/{{ item.name }}-s3cfg ls s3://{{ item.bucket }}/*.gz.parquet
  register: list_files_s3
  async: 600
  poll: 0
  with_items: "{{ _s3.users }}"
- debug: msg={{ list_files_s3 }}
  when: print_debug == true


- name: Delete s3cmd Test Directory
  file:
    path: "{{ _s3.base_path }}/s3cmd"
    state: absent
  register: del_s3cmd_dir
  with_items: "{{ _s3.users }}"
- debug: msg={{ del_s3cmd_dir }}
  when: print_debug == true


- name: Uninstall S3 Client Packages
  package: name={{ item }} state=absent
  with_items:
    - "s3cmd"

