#  with_items:
#    - "part-m-00001.gz.parquet"
#    - "part-m-00003.gz.parquet"
#    - "part-m-00005.gz.parquet"
#    - "part-m-00000.gz.parquet"
#    - "part-m-00002.gz.parquet"
#    - "part-m-00004.gz.parquet"
#    - "part-m-00006.gz.parquet"

# Example
# s3cmd del s3://BUCKET/OBJECT
# s3cmd del -r s3://BUCKET/FOLDER
# s3cmd  ls s3://BucketName/foldername_prefix* |awk '{print $2}' | while read files; do s3cmd  rm -r $files; done
# s3cmd rm s3://mybucket/myfileidontwant --force

- name: Delete Parquet Test Files in S3 Backends
  shell: |
    s3cmd --no-check-certificate --config=/root/s3cmd/{{ item.name }}-s3cfg del -r s3://{{ item.bucket }}/*.gz.parquet
  register: del_parq_files_s3
  ignore_errors: true
  with_items: "{{ s3.users }}"
- debug: msg={{ del_parq_files_s3 }}
  when: print_debug == true

#
- name: Delete s3cmd Test Directory
  file:
    path: "/root/s3cmd"
    state: absent
  register: del_s3cmd_dir
  ignore_errors: true
  with_items: "{{ s3.users }}"
- debug: msg={{ del_s3cmd_dir }}
  when: print_debug == true

#
- name: Uninstall S3 Client Packages for Linux
  become: true
  package: name={{ item }} state=absent
  ignore_errors: true
  with_items: "s3cmd"

