smb:
  cluster:
    name: smb-clu01
  ad:
    domain: jtest.weka.io
    netbios: JTEST
    users:
      admin:
        id: Administrator
        pass: Changeme12\!\@
  net:
    ips_range: 192.168.1.241-245
    client_ip: 192.168.1.241
  fs:
    name: smb-fs01
    mount_dir: /mnt/smb-fs01
    mount_point: smb-fs01
  share:
    name: smb-share-01

