---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Initialize Hosts for
  import_tasks: init-hosts.yml
  tags: install
  when: inventory_hostname in groups['workers']

#
- name: Install for
  import_tasks: install.yml
  tags: install
  when: inventory_hostname in groups['workers']

#
- name: Install for
  import_tasks: ssh_sudo_user.yml
  tags: install
  when: inventory_hostname in groups['workers']

#
- name: Install for
  import_tasks: ssh_root_user.yml
  tags: install
  when: inventory_hostname in groups['workers']

#
- name: Uninstall for
  import_tasks: uninstall.yml
  tags: uninstall
  when: inventory_hostname in groups['workers']

