---
- name: Cleanup the NVME Block Devices
  shell: |
    pvremove -y -ff {{ item }}
    dd if=/dev/zero of={{ item }} bs=4096 count=1 conv=notrunc
    nvme format {{ item }}
    wipefs -a {{ item }}
    sgdisk --zap-all --delete {{ item }}
    blkdiscard {{ item }}
  register: cleanup_nvme_block_devices
  ignore_errors: true
  with_items: "{{ nvme_device_array }}"
- debug: msg={{ cleanup_nvme_block_devices }}
  when: print_debug == true

