---
- name: Copy Force Destroy MCB Script
  template: src=force-destroy-mcb.sh.j2 dest={{ _weka.base_path }}/force-destroy-mcb.sh owner=root group=root mode=755 force=yes


- name: Force Destroy MCB
  shell: |
    {{ _weka.base_path }}/force-destroy-mcb.sh 2>&1 | wc -l
  register: force_destroy_mcb
  until: force_destroy_mcb.stdout|int == 4
  retries: 50
  delay: 10

