---
- name: Copy Force Destroy SCB Script
  template: src=force-destroy-scb.sh.j2 dest={{ _weka.base_path }}/force-destroy-scb.sh owner=root group=root mode=755 force=yes


- name: Force Destroy SCB
  shell: |
    {{ _weka.base_path }}/force-destroy-scb.sh 2>&1 | wc -l
  register: force_destroy_scb
  until: force_destroy_scb.stdout|int == 1
  retries: 50
  delay: 10

