---
- name: Check OS ( Weka NFS )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'


- name: Set facts
  import_tasks: set-facts.yml
  tags: deploy, destroy, install, uninstall
  when: inventory_hostname in groups['workers']


- name: Deploy NFS Backends
  import_tasks: deploy-nfs-backend.yml
  tags: deploy, create, install
  when: ( backend is defined and backend == true ) and inventory_hostname in groups['control']


- name: Setup NFS Clients
  import_tasks: setup-nfs-clients.yml
  tags: setup, create, install
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']


- name: Remove NFS Clients
  import_tasks: remove-nfs-clients.yml
  tags: remove, delete, uninstall
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']


- name: Destroy NFS Backends
  import_tasks: destroy-nfs-backend.yml
  tags: destroy, remove, uninstall
  when: ( backend is defined and backend == true ) and inventory_hostname in groups['control']

