---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'

#
- name: Set facts
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall
  when: inventory_hostname in groups['workers']

#
- name: Install NFS Backends
  import_tasks: install.yml
  tags: install
  when: weka.backend.nfs == true and inventory_hostname in groups['workers']

#
- name: Install NFS Clients
  import_tasks: install-clients.yml
  tags: install
  when: weka.client.nfs == true and inventory_hostname in groups['clients']

#
- name: Uninstall NFS Clients
  import_tasks: uninstall-clients.yml
  tags: uninstall
  when: weka.client.nfs == true and inventory_hostname in groups['clients']

#
- name: Uninstall NFS Backends
  import_tasks: uninstall.yml
  tags: uninstall
  when: weka.backend.nfs == true and inventory_hostname in groups['workers']

