---
- name:  Enable Devel Package Repository
  shell: |
    dnf config-manager --set-enabled devel
  register: enable_devel_repo
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky"
- debug: msg={{ enable_devel_repo }}
  when: print_debug == true and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" )


- name: Install NFS Client Packages
  package: name={{item}} state=present
  with_items:
    - "nfs-utils"
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky"


- name: Install NFS Client Packages
  package: name={{item}} state=present
  with_items:
    - "nfs-client"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"


- name: Create Directory to Mount NFS
  file:
    path: "{{ _nfs.fs.mount_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: yes
  register: create_nfs_dir
- debug: msg={{ create_nfs_dir }}
  when: print_debug == true


- name: Mount Ephemeral NFS Volume
  mount:
    src: "{{ _nfs.net.ips_range | split('-') | first }}:/{{ _nfs.fs.config }}"
    path: "{{ _nfs.fs.mount_dir }}"
    opts: ""
    fstype: nfs
    state: ephemeral
  register: mount_nfs_dir
- debug: msg={{ mount_nfs_dir }}
  when: print_debug == true


- name: Create a File with the Content
  copy:
    content: "Hellow Weka NFS-W World!"
    dest: "{{ _nfs.fs.mount_dir }}/test-nfs01.txt"
    force: no
    owner: root
    group: root
    mode: 0644

