weka:
  cluster_name: jclu01
  major_version: 4
  minor_version: 2
  build_version: 8
  patch_version: 66
  base_path: /root
  admin_user: admin
  admin_default_pass: admin
  admin_change_pass: "Changeme12!@"
  download: false
  bin_type: tar
  tools:             # git clone https://github.com/weka/tools; cd tools ; git checkout v1.3.8
    name: tools
    major_version: 1
    minor_version: 3
    patch_version: 8
    download: false
    bin_type: tar.gz
  allow_unsupported_devices: true
  default_mem_size: 3GiB
  use_res_gen: false
container:
   compute:
     num: "1"
     memory: "4GiB"       # 0 means automatical allocation
     cpu_core_num: "1"
     cpu_core_ids: "10,11,12,13,14,15"
     port: "14200"
   drives:
     num: "2"
     memory: "5GiB"       # 0 means automatical allocation
     cpu_core_num: "2"
     cpu_core_ids: "8,9"
     data: "3"
     parity: "2"
     hotspare: "0"          # 0 means automaical allocation
     devices: "/dev/sdc /dev/sdd"
     port: "14000"
   frontend:
     num: "1"
     memory: "2.5GiB"
     cpu_core_num: "1"
     cpu_core_ids: "7"
     port: "14400"
wekafs:
  group:
    - { name: "jtest-default-grp01" }
    - { name: "jtest-wekafs-grp01" }
    - { name: "jtest-obs-grp01" }
    - { name: "jtest-s3-grp01" }
    - { name: "jtest-nfs-grp01" }
    - { name: "jtest-smb-grp01" }
  fs:
    - { name: "jtest-default-fs01",  grp_name: "jtest-default-grp01", size : "6GiB", mount_dir : "/mnt/jtest-default-fs01" }
    - { name: "jtest-wekafs-fs01",  grp_name: "jtest-wekafs-grp01", size : "6GiB", mount_dir : "/mnt/jtest-wekafs-fs01" }
    - { name: "jtest-obs-fs01",  grp_name: "jtest-obs-grp01", size : "6GiB", mount_dir : "/mnt/jtest-obs-fs01" }
    - { name: "jtest-s3-fs01",  grp_name: "jtest-s3-grp01", size : "6GiB", mount_dir : "/mnt/jtest-s3-fs01" }
    - { name: "jtest-nfs-fs01",  grp_name: "jtest-nfs-grp01", size : "6GiB", mount_dir : "/mnt/jtest-nfs-fs01" }
    - { name: "jtest-smb-fs01",  grp_name: "jtest-smb-grp01", size : "6GiB", mount_dir : "/mnt/jtest-smb-fs01" }

    # - { name: "jtest-s3-config-fs01",  grp_name: "jtest-default-grp01", size : "6GiB", mount_dir : "/mnt/jtest-s3-config-fs01" }

#
# https://www.notion.so/wekaio/Which-ports-required-by-weka-28a849675f474822a5a034ab5d30fcff
#
# Weka Port Ranges
# https://docs.weka.io/install/prerequisites-and-compatibility#networking

