weka:
  major_version: 4
  minor_version: 2
  build_version: 7
  patch_version: 64
  base_path: /root
  bin_type: tar
  admin_user: admin
  admin_default_pass: admin
  admin_change_pass: "Changeme12!@"
  download: false
wekafs:
  group: jtest-group01
  fs: jtest-fs01
  size: 7GiB
  mount_dir: /mnt/jtest-weka-mnt01
cpu_cores:
  container_max_id: "{{ groups['workers'] | length -1 }}"
  container_num: 3
  drives_num: 1
  compute_num: 2
  frontends_num: 0
drives:
  data: 3
  parity: 2
