upload_weka_bin: false
remove_weka_bin: false
setup_weka_bin: false
destroy_weka: true
# first_addrs_num: "{{ weka.host_num|int % 2 | int }}"
# second_addrs_num: "{{ weka.host_num|int % 2 | int }}"

container:
   total_cores: "4"                 # Total_cores sholud be same as number of virtual network adpaters hold by a SCB default container for DPDK in Virtual Environment
   spare_memory: "8GiB"
   weka_huge_page_memory: "1.4GiB"
   default:
     name: "jack-kr-scb"
     mem_size: "5GiB"
     port: 14000
   drives:
     name: "drives0"
     cores: "1"
     memory: "2.4GiB"                # 2.3GiB default, 0 means automatical allocation
     core_ids: "1,2"
     data: "3"
     parity: "2"
     hotspare: "1"                   # 0 means automaical allocation
     devices: "/dev/sdb /dev/sdc"
     port: "14000"
     options:
   compute:
     name: "compute0"
     cores: "1"
     memory: "3.4GiB"                # 3.3GiB default, 0 means automatical allocation
     core_ids: "3,4"
     port: "14200"
     options:                        # "--allow-mix-setting"
   frontend:
     name: "frontend0"
     cores: "1"
     memory: "2.4GiB"                # 2.3 GiB default
     core_ids: "8"
     port: "14400"
     options:                        # "--allow-mix-setting"
   envoy:
     name: envoy
   protocol:
     memory: "0GiB"

# Weka Port Ranges
# https://docs.weka.io/install/prerequisites-and-compatibility#networking
# https://www.notion.so/wekaio/Which-ports-required-by-weka-28a849675f474822a5a034ab5d30fcff

