remove_weka_bin: false
setup_weka_bin: true
destroy_weka: true
# first_addrs_num: "{{ weka.host_num|int % 2 | int }}"
# second_addrs_num: "{{ weka.host_num|int % 2 | int }}"

# Total_cores sholud be same as number of virtual network adpaters hold by a SCB default container for DPDK in Virtual Environment
# total_cores: "{{ container.drives.cores|int + container.compute.cores|int + container.frontend.cores|int }}"
container:
   total_cores: "4"
   spare_memory: "8GiB"
   weka_huge_page_memory: "1.4GiB"
   default:
     name: "default"              # name: "jack-kr-scb" - It's very strange that there are network errors, SYNC, DOWN not UP in case that container name is not default.
     mem_size: "9GiB"
     port: 14000
   drives:
     name: "drives0"
     cores: "1"
     memory: "5GiB"             # 2.3GiB default, 0 means automatical allocation
     core_ids: "1,2"
     data: "3"
     parity: "2"
     hotspare: "0"                # 0 means automaical allocation
     devices: "/dev/sdb /dev/sdc"
     port: "14000"
     options:
   compute:
     name: "compute0"
     cores: "1"
     memory: "3.5GiB"             # 3.3GiB default, 0 means automatical allocation
     core_ids: "3,4"
     port: "14200"
     options:                     # "--allow-mix-setting"
   frontend:
     name: "frontend0"
     cores: "1"
     memory: "2.5GiB"             # 2.3 GiB default
     core_ids: "8"
     port: "14400"
     options:                     # "--allow-mix-setting"
   envoy:
     name: envoy
   protocol:
     memory: "0GiB"

# Weka Port Ranges
# https://docs.weka.io/install/prerequisites-and-compatibility#networking
# https://www.notion.so/wekaio/Which-ports-required-by-weka-28a849675f474822a5a034ab5d30fcff
