weka:
  major_version: 4
  minor_version: 2
  build_version: 7
  patch_version: 64
  base_path: /root
  bin_type: tar
  admin_user: admin
  admin_default_pass: admin
  admin_change_pass: "Changeme12!@"
  download: false
wekafs:
  group: default
  fs: default
  size: 5GiB
