nfs:
  interface:
    group: floating-nfs-ip
  client:
    group: client-nfs
  net:
    ifname: eth5
    network: 192.168.1.0
    subnet: 255.255.255.0
    gateway: 192.168.1.1
    ips_range: 192.168.1.241-245
  fs:
    config: default-fs01
    mount_dir: /mnt/nfs-fs01
    wekafs: nfs-fs01

# weka nfs global-config set --config-fs default-fs01
# NFS config FS capacity can't be lower than 5368709120

