nfs:
  interface:
    group: floating-nfs-ip
  client:
    group: client-nfs
  net:
    ifname: eth5
    network: 192.168.1.0
    subnet: 255.255.255.0
    gateway: 192.168.1.1
    iprange: 192.168.1.241-245
  fs:
    config: default-fs01
