---
- name: Check OS ( Weka OBS )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'


- name: Deploy Object Storage Tier
  import_tasks: deploy-obs-tier.yml
  tags: deploy, setup, install
  when: ( tier is defined and tier == true ) and inventory_hostname in groups['control']


- name: Remove S3 Object Storage Tier
  import_tasks: destroy-obs-tier.yml
  tags: destroy, remove, uninstall
  when: ( tier is defined and tier == true ) and inventory_hostname in groups['control']
  # when: ( tier is defined and tier == true ) and inventory_hostname in groups['workers']

