#
# - debug: msg={{ "Disable object store" }}

# $ weka s3 bucket create name jtest-bucket01 --policy public --policy-json
# Cannot pass option "policy-json" for command "weka s3 bucket create" without its value, please make sure to pass a value and check that the format is correct if a value was passed


# $ weka user login admin Changeme12\!\@
# +------------------------------+
# | Login completed successfully |
# +------------------------------+

# $ weka s3 bucket create jtest-bucket01 --policy public
# error: Internal error: core.exception.RangeError: Index/key not found
# in FileSystemRow[RawTypedIdentifier!("FSId", uint, 4294967295u, 4294967295u, FMT(""), false)] :
# FSId<4294967295>

# $ weka fs
# FILESYSTEM ID  FILESYSTEM NAME  USED SSD  AVAILABLE SSD  USED TOTAL  AVAILABLE TOTAL  THIN PROVISIONED  THIN PROVISIONED MINIMUM SSD  THIN PROVISIONED MAXIMUM SSD
# 0              jtest-fs01       20.47 KB  7.51 GB        20.47 KB    7.51 GB          False

# $ weka s3 bucket create jtest-bucket01 --policy public --fs-name jtest-fs01
# error: Could not find a running S3 container to run the command in

# $ weka s3 bucket create jtest-bucket01 --policy public --fs-name jtest-fs01 --fs-id 0
# error: Only one of fs-name or fs-id can be used

#
#- name:  Delete WekaFS attached into Object Store
#  shell: |
#    weka fs delete s3fs -f
# register: delete_s3fs
#  ignore_errors: true
#  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
#- debug: msg={{ delete_s3fs }}
#

#
- name: Delete OBS directory to mount WekaFS
  shell: |
    umount /mnt/{{ obs.fs.name }}
    rm -rf /mnt/{{ obs.fs.name }}
  register: delete_obsfs_dir
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ delete_obsfs_dir  }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name:  Delete WekaFS attached into Object Store Tier
  shell: |
    weka fs delete {{ obs.tier.fs.name }} -f
  register: update_obs_fs_grp
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ update_obs_fs_grp }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
  #  weka fs delete {{ obs.tier.fs.name }} -f --purge-from-obs

### Here need to check bucket still using

#
- name:  Delete Object Store Tier
  shell: |
    weka fs tier s3 delete {{ obs.tier.name }}
  register: delete_obs_tier
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ delete_obs_tier }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name:  Delete Object Store
  shell: |
    weka fs tier obs delete {{ obs.name }}
  register: delete_obs
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ delete_obs }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
# error: Operation not allowed. test-snap01 in obs-new-fs01 is currently synchronizing, please try again later.
# weka fs snapshot delete obs-new-fs01 test-snap01 -f
#
# error: Snapshot test-snap01 in filesystem obs-new-fs01 is being deleted.
#

# weka fs snapshot
# SNAPSHOT ID  FILESYSTEM    NAME         ACCESS POINT              IS WRITABLE  CREATION TIME        LOCAL OBJECT STATUS  LOCAL OBJECT PROGRESS  REMOTE OBJECT STATUS  REMOTE OBJECT PROGRESS  IS BEING REMOVED
# 14          obs-new-fs01  test-snap01  @GMT-2024.03.24-12.23.59  False        2024-03-24T21:23:59  UPLOADING            6%                     NONE                  N/A
# True

# Above error could be fixed after reconfiguring tiering correctly. In jack's case, wrong port 9000 was configured mistakenly for minio s3

# weka fs tier release
# weka fs tier release --non-existing error
# weka fs tier release --non-existing warn
# weka fs tier release --non-existing ignore

# weka fs snapshot download obs-new-fs01 /mnt
# error: Operation is forbidden: Incremental snapshot download is not supported on this version

