---
#
- name: Restart haproxy service
  systemd:
    daemon_reload: true
    name: haproxy
    enabled: true
    state: restarted
  listen: "restart haproxy"

#
- name: Check HAProxy is started and accepting connections
  wait_for:
    port: 7000
    host: "{{ hostvars[inventory_hostname].ansible_ssh_host }}"
    state: started
    timeout: 120
    delay: 10
  ignore_errors: false
  listen: "restart haproxy"

#- name: Check HAProxy is started and accepting connections
#  local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started delay=10 timeout=300 connect_timeout=300 search_regex=OpenSSH
#  become: no
