#
- name: Define fact for weka version
  set_fact:
    weka_file_name: weka-{{ weka.major_version }}.{{ weka.minor_version }}.{{ weka.build_version }}{{ weka.patch_version }}
- debug: msg={{ weka_file_name }}

#
- name: Install Weka binary
  shell: |
    cd {{ weka.base_path }}/{{ weka_file_name }} ; ./install.sh
  register: install_weka_binary
  when: inventory_hostname in groups['clients']
  # when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']
- debug: msg={{ install_weka_binary }}
  when: print_debug == true and inventory_hostname in groups['clients']
  # when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Install WekaFS Client
  shell: |
    curl {{ item }}:14000/dist/v1/install | sh
  delegate_to: "{{ hostvars[groups['clients'][0]]['ansible_hostname'] }}"
  delegate_facts: True
  register: install_wekafs_client
  with_items:
    - "{{ ipaddr0 }}"
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ install_wekafs_client }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Create directory to mount WekaFS
  shell: |
    mkdir {{ wekafs.fs[1].mount_dir }}
  register: create_wekafs_dir
  when: inventory_hostname in groups['clients']
- debug: msg={{ create_wekafs_dir  }}
  when: print_debug == true and inventory_hostname in groups['clients']

#
- name: Mount WekaFS directory
  shell: |
    mount -t wekafs -o net=eth1 192.168.1.201/{{ wekafs.fs[1].name }} {{ wekafs.fs[1].mount_dir }}
  delegate_to: "{{ hostvars[groups['clients'][0]]['ansible_hostname'] }}"
  delegate_facts: True
  register: mount_wekafs_dir
  with_items:
    - { netdev: "{{ netdev0 }}", ipaddr: "{{ ipaddr0 }}" }
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- debug: msg={{ mount_wekafs_dir }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Check if WekaFS directory is mounted
  shell: |
    df -h
    ls -al {{ wekafs.fs[1].mount_dir }}
  register: check_wekafs_mounted
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ check_wekafs_mounted  }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Creat text file with the content
  shell: |
    touch {{ wekafs.fs[1].mount_dir }}/test01.txt
    echo "hello world" >  {{ wekafs.fs[1].mount_dir }}/test01.txt
    cat {{ wekafs.fs[1].mount_dir }}/test01.txt
  register: create_wekafs_file
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ create_wekafs_file }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

# curl 192.168.0.171:14000/dist/v1/install | sh
# weka version get 4.2.9.29-hcsf
# weka version set 4.2.9.29-hcsf
# weka local start client


# ./wekadestroy -u -f -y rk8-node06
# curl 192.168.1.211:14000/dist/v1/install | sh  # 211 is management's ip address hold by drives0 container
#
# mount -t wekafs -o num_cores=1 -o net=eth5/192.168.1.216/24/192.168.1.1 192.168.1.211/jtest-wekafs-fs01 /mnt/jtest-wekafs-fs01
# eth5 is client network device which mtu must be 9000 if it's not, client will be failed
# 211 is management's ip address hold by drives0 container
#
# After succesfully mounted, frontend got DPDK
#
# weka cluster process | grep client
# 300         rk8-node06  client     192.168.1.186  UP      4.2.9.29-hcsf  MANAGEMENT  UDP                    0:07:20h  Configuration snapshot pulled (7 minutes ago)
# 301         rk8-node06  client     192.168.1.216  UP      4.2.9.29-hcsf  FRONTEND    DPDK     1    1.47 GB  0:07:17h
#
# ******
# Need to test switch mode of iptime in order to expand ports from 5 to 10

