---
- name: Check OS ( WekaFS )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'
    - inventory_hostname in groups['workers']


- name: Set Facts for Setup and Remove Weka File Sysetm and Clients
  import_tasks: facts/set-net-facts.yml
  tags: create, setup, install, uninstall, remove, delete
  when: inventory_hostname in groups['clients'] or inventory_hostname in groups['control']
  # when: ( fs is defined and fs == true ) and ( inventory_hostname in groups['clients'] or inventory_hostname in groups['control'] )
  # when: _weka.client.wekafs == true and ( inventory_hostname in groups['clients'] or inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname'] )


#- name: Set Facts for Setup and Remove Weka File Sysetm and Clients
#  import_tasks: set-wekafs-facts.yml
#  tags: install, uninstall
#  when: inventory_hostname in groups['workers']


- name: Set Facts for Setup WekaFS and POSIX Clients
  import_tasks: facts/set-clients-facts.yml
  tags: create, setup, install
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']
  # when: _weka.client.wekafs == true and inventory_hostname in groups['clients']


- name: Set facts for WekaFS POSIX Clients at Virtualization such as VMware and Public Cloud
  import_tasks: facts/set-virt-clients-facts.yml
  tags: create, setup, install
  when: (( client is defined and client == true ) and ( _weka.client.net.type == "virtual" )) and inventory_hostname in groups['clients']
  # when: _weka.client.wekafs == true and _weka.client.net.type == "virtual" and inventory_hostname in groups['clients']


- name: Create WekaFS
  import_tasks: create-fs.yml
  tags: create, install
  when: ( fs is defined and fs == true ) and inventory_hostname in groups['control']


- name: Remove WekaFS
  import_tasks: remove-fs.yml
  tags: delete, remove, uninstall
  when: ( fs is defined and fs == true ) and inventory_hostname in groups['control']


- name: Setup WekaFS Client
  import_tasks: setup-clients.yml
  tags: setup, create, install
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']
  # when: (( client is defined and client == true ) and ( fs is defined and fs == true ))_and inventory_hostname in groups['clients']
  # when: _weka.client.wekafs == true and inventory_hostname in groups['clients']


- name: Remove WekaFS Clients
  import_tasks: remove-clients.yml
  tags: delete, remove, uninstall
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']
  # when: (( client is defined and client == true ) and ( fs is defined and fs == true ))_and inventory_hostname in groups['clients']
  # when: _weka.client.wekafs == true and inventory_hostname in groups['clients']


- name: Force Destroy WekaFs Client Containers
  import_tasks: ext/force-destroy-client.yml
  tags: destroy, uninstall
  when: (( client is defined and client == true ) and ( force is defined and force == true )) and inventory_hostname in groups['clients']


