---
# For now fail if it's not suppoted OS
#- name: Check OS
#  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
#  when:
#    - ansible_distribution_major_version|int >= 8
#    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'

#
- name: Set facts for Setup and Remove Weka File Sysetm and Clients
  import_tasks: set-weka-facts.yml
  tags:
    - install
    - uninstall
  when: inventory_hostname in groups['workers']

#
#- name: Set facts for Delegating Network Device Name and IP Address of Endpoint to Connect from Clients
#  import_tasks: set-backend-net-facts.yml
#  tags:
#    - install
#    - uninstall
#  when: inventory_hostname in groups['workers']

#
- name: Set facts for Setup and Remove Weka File Sysetm and Clients
  import_tasks: set-clients-facts.yml
  tags: install
  when: weka.client.wekafs == true and inventory_hostname in groups['clients']

#
- name: Install WekaFS
  import_tasks: install.yml
  tags: install
  when: weka.fs == true and inventory_hostname in groups['workers']

#
- name: Install WekaFS Client
  import_tasks: install-clients.yml
  tags: install
  when: weka.client.wekafs == true and inventory_hostname in groups['clients']
  # when: weka.client.wekafs == true and wekafs.clients_only == true and  ( inventory_hostname in groups['clients'] or inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname'] )

#
- name: Uninstall WekaFS Clients
  import_tasks: uninstall-clients.yml
  tags: uninstall
  when: weka.client.wekafs == true and inventory_hostname in groups['clients']

#
- name: Uninstall WekaFS
  import_tasks: uninstall.yml
  tags: uninstall
  when: weka.fs == true and inventory_hostname in groups['workers']

