---
- name: Delete Custom WekaFS
  shell: |
    weka fs delete {{ item.name }} -f
  register: delete_custom_wekafs
  ignore_errors: true
  with_items:
    - "{{ _wekafs.fs.default }}"
    - "{{ _wekafs.fs.filesystem }}"
    - "{{ _wekafs.fs.obs }}"
    - "{{ _wekafs.fs.s3 }}"
    - "{{ _wekafs.fs.nfs }}"
    - "{{ _wekafs.fs.smb }}"
- debug: msg={{ delete_custom_wekafs }}


- name: Delete Custom WekaFS Group
  shell: |
    weka fs group delete {{ item.name }}
  register: delete_wekafs_group
  with_items: "{{ _wekafs.group }}"
  ignore_errors: true
- debug: msg={{ delete_wekafs_group }}


- name: Check Custom WekaFS
  shell: |
    weka fs
  register: check_custom_wekafs
  ignore_errors: true
- debug: msg={{ check_custom_wekafs }}


- name: Check WekaFS in the Containers
  shell: |
    weka cluster container
  register: check_wekafs_container
  ignore_errors: true
- debug: msg={{ check_wekafs_container }}

