#
- name: Delete text file with the content
  shell: |
    rm -rf /mnt/jtest-obs-fs01/obs-test01.txt
    rm -rf /mnt/jtest-obs-fs01/test01.txt
    rm -rf /mnt/jtest-obs-fs01/dirtest
    # rm -f {{ wekafs.fs[0].mount_dir }}/test01.txt
  register: delete_wekafs_file
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ delete_wekafs_file }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Check if WekaFS directory is mounted
  shell: |
    df -h
    ls -al /mnt/jtest-obs-fs01
    # ls -al {{ wekafs.fs[0].mount_dir }}
  register: check_wekafs_mounted
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ check_wekafs_mounted  }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Unmount WekaFS directory
  shell: |
    umount /mnt/jtest-obs-fs01
    # umount {{ wekafs.fs[0].mount_dir }}
  register: unmount_wekafs_dir
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ unmount_wekafs_dir }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Delete directory to mount WekaFS
  shell: |
    rm -rf /mnt/jtest-obs-fs01
    # rm -rf {{ wekafs.fs[0].mount_dir }}
  register: delete_wekafs_dir
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']
- debug: msg={{ delete_wekafs_dir }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Destroy Weka Client
  shell: |
    cd /root/tools/install ; ./wekadestroy --yes --force --uninstall {{ hostvars[groups['clients'][0]]['ansible_hostname'] }}
  register: destroy_weka_client
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

- debug: msg={{ destroy_weka_client }}
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
#- name: Reboot required
#  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible updates triggered" ) &
#  async: 1200
#  poll: 0
#  when: ( print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname'] ) and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" )
#  notify:
#    - Waiting for server to come back after reboot
#
#- meta: flush_handlers
#  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']

#
- name: Reboot required ( Red Hat ) - Step 1 in RHEL/CentOS/Rocky Linux 8
  command: /usr/bin/needs-restarting -r
  register: reboot_required
  changed_when: False
  when: ( print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname'] ) and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8
# ignore_errors: True

- debug: msg={{ reboot_required }}
  when: ( print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname'] ) and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" )
#
- name: Reboot required ( Red Hat ) - Step 2
  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible updates triggered" ) &
  async: 1200
  poll: 0
  notify:
    - Waiting for server to come back after reboot
  when: ( print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname'] ) and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8 and reboot_required.rc == 1

- meta: flush_handlers
  when: print_debug == true and inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']


#
#- name: Uninstall WekaFS Client
#  shell: |
#    curl {{ hostvars[groups['workers'][0]]['ansible_eth0']['ipv4']['address'] }}:14000/dist/v1/install | sh
#  register: uninstall_wekafs_client
#  when: inventory_hostname in hostvars[groups['clients'][0]]['ansible_hostname']
#- debug: msg={{ uninstall_wekafs_client }}

