#
- name: Create S3 Cluster
  shell: |
    # weka cluster host | awk '{print $1}' | sed -e 1d | tr '\n' ',' | sed 's/,$/\n/'
    weka cluster container | awk '{print $1}' | sed -e 1d | tr '\n' ',' | sed 's/,$/\n/'
  register: all_container_ids
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- debug: msg={{ all_container_ids }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Create S3 Cluster
  shell: |
    weka s3 cluster create jtest-s3-fs01 jtest-default-fs01 --container {{ all_container_ids.stdout }}
    # weka s3 cluster create --config-fs-name jtest-s3-fs01 jtest-default-fs01 --host 12,13,14
  register: create_s3_cluster
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ create_s3_cluster }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Validate if S3 Cluster is Online
  shell: weka s3 cluster status
  register: check_s3_cluster_status
  until: check_s3_cluster_status.stdout.find("Not Ready") == -1
  retries: 50
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ check_s3_cluster_status }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Create S3 Bucket
  shell: |
    weka s3 bucket create jtest-s3-bucket01
  register: create_s3_bucket
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ create_s3_bucket }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Copy expect script file to add s3 user
  copy: src=add-s3-user.sh dest=/root/add-s3-user.sh mode=0755 owner=root group=root
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Add s3 user
  shell: /root/add-s3-user.sh
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- name: Attache readwrite permission
  shell: weka s3 policy attach readwrite jomoon
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

