- name: Enable and Start Firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started
  when: inventory_hostname in groups['workers']

- name: Reset ruleset for public zone in firewalld
  shell: |
    firewall-cmd --load-zone-defaults=public --permanent
    firewall-cmd --reload
  when: inventory_hostname in groups['workers']

- name: Set Firewalld Port Policy for Name nodes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  loop: "{{ weka_ports }}"
  when: inventory_hostname in groups['workers']
#  notify: firewall restart
