#
- name: Enable and Start Firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started
  when: inventory_hostname in groups['workers']

#
- name: Reset ruleset for public zone in firewalld
  shell: |
    firewall-cmd --load-zone-defaults=public --permanent
    firewall-cmd --reload
  when: inventory_hostname in groups['all']

#
- name: Set Firewalld Port Policy for Weka Cluster
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  loop: "{{ weka_cluster_ports }}"
#    - "{{ drives_ports }}"
#    - "{{ frontedns_ports }}"
#    - "{{ compute_ports }}"
  when: inventory_hostname in groups['workers']
  notify: Start Firewalld

#
#- name: Set Firewalld Port Policy for Weka Clients
#  firewalld:
#    port: "{{ item }}/tcp"
#    permanent: true
#    state: enabled
#    zone: public
#    immediate: yes
#  loop: "{{ wekafs_client_ports }}"
#  when: inventory_hostname in groups['clients']
#  notify: Start Firewalld

