#
- name: Disable Firewalld Port Policy for Weka Cluster
  firewalld:
    port: "{{ item }}/tcp"
    state: disabled
    zone: public
    permanent: true
    immediate: yes
  loop: "{{ weka_cluster_ports }}"
  when: inventory_hostname in groups['workers']
  notify: Retart Firewalld

#
- name: Disable Firewalld Port Policy for WekaFS Client
  firewalld:
    port: "{{ item }}/tcp"
    state: disabled
    zone: public
    permanent: true
    immediate: yes
  loop: "{{ wekafs_client_orts }}"
  when: inventory_hostname in groups['clients']
  notify: Restart Firewalld


#    - "{{ drives_ports }}"
#    - "{{ frontedns_ports }}"
#    - "{{ compute_ports }}"

# - name: Disable Firewalld Port Policy for Weka Clients
#  firewalld: port={{ item }}/tcp permanent=true state=disabled zone=public immediate=yes
#  loop:
#    - "{{ wekafs_client_ports }}"
#  when: inventory_hostname in groups['clients']
#  notify: Start Firewalld

#
- name: Reset ruleset for public zone in firewalld
  shell: |
    firewall-cmd --load-zone-defaults=public --permanent
    firewall-cmd --reload
  when: inventory_hostname in groups['all']

#
- name: Disable and Stop Firewalld
  service:
    name: firewalld
    state: stopped
  when: inventory_hostname in groups['all']

