---
- name: Restart System
  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible updates triggered" ) &
  async: 300
  poll: 0


- name: Waiting for Server to Come Back after Reboot
  local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started delay=10 timeout=300 connect_timeout=300 search_regex=OpenSSH
  become: no


- name: Reload Sysctl
  shell: |
    /sbin/sysctl -p
    /sbin/sysctl -p /etc/sysctl.conf


- name: Reload SSHd
  service:
    name: sshd
    state: reloaded

