---
- name: Umount SMB Directory
  mount:
    path: "{{ _smb.fs.mount_dir }}"
    state: unmounted
  retries: 10
  delay: 10
  register: umount_smb_wekafs
- debug: msg={{ umount_smb_wekafs }}
  when: print_debug == true
# umount -f -l {{ smb.fs.mount_dir }}


- name: Delete Mounted directory
  file:
    state: absent
    path: "{{ _smb.fs.mount_dir }}"
  register: delete_smb_files
- debug: msg={{ delete_smb_files }}
  when: print_debug == true


- name: Get All Share IDs
  shell: |
    weka smb share | sed 1d | awk '{print $2}'
  register: all_share_ids
- debug: msg={{ all_share_ids }}
  when: print_debug == true
 

- name: Remove All Share IDs
  shell: |
    weka smb share remove {{ item }} -f
  register: remove_all_share_ids
  with_items: "{{ all_share_ids.stdout_lines }}"
  when: "'' not in remove_all_share_ids.stdout"
- debug: msg={{ remove_all_share_ids }}
  when: print_debug == true


- name: Get All SMB Contaienr IDs for SCB Cluster
  shell: |
    weka cluster container | awk '{print $1}' | sed -e 1d | tr '\n' ',' | sed 's/,$/\n/'
  register: all_container_ids
  when: _weka.backend.scb == true


- name: Get All SMB Contaienr IDs for MCB Cluster
  shell: |
    weka cluster container | grep frontend | awk '{print $1}' | tr '\n' ',' | sed 's/,$/\n/'
  register: all_container_ids
  when: _weka.backend.mcb == true


- debug: msg={{ all_container_ids }}
  when: print_debug == true


# - name: Remove SMB Containers
#   shell: |
#    weka smb cluster containers remove --container-ids {{ all_container_ids.stdout }} --force
#  register: remove_smb_containers
#- debug: msg={{ remove_smb_containers }}
#  when: print_debug == true
#  error: SMB cluster must have at least 3 hosts to function as a cluster


- name: Leave from AD
  shell: |
    weka smb domain leave {{ _smb.ad.users.admin.id }} {{ _smb.ad.users.admin.pass }}
  register: leave_ad
  ignore_errors: true
- debug: msg={{ leave_ad }}
  when: print_debug == true
# until: leave_ad is succeeded
# retries: 10
# delay: 180


- name: Destroy SMB Cluster
  shell: |
    weka smb cluster destroy -f
  register: destroy_smb_cluster
  ignore_errors: true
- debug: msg={{ destroy_smb_cluster }}
  when: print_debug == true


