# Setup: SMB service on WEKA

# Check that the ID mapping backend is “rfc2307”
# weka smb cluster
#
# And that the Active Directory has been joined
# weka smb domain
#
# Optional, but useful: setting up DNS A records for either the SMB-running Backends or
# the Floating IPs allows you to access the SMB service by name (and also allows the use of the strongly-preferred later authentication algorithms).
# PS C:\Users\Administrator> Add-DnsServerResourceRecordA -Name "wekasmb" -ZoneName "ad.example.com" -AllowUpdateAny -IPv4Address "192.168.114.100"
# https://www.notion.so/wekaio/Multi-protocol-SMB-and-NFS-single-filesystem-access-8abcd9d23e004549a66e2e98fbcbd787?pvs=4

# For debug and open a 2224 port by firewalld
# weka local exec --container smbw /usr/sbin/pcs cluster status
# weka smb cluster update


- name: Check if MCB and SCB both are enabled to deploy in groups_vars/all.yml
  fail: msg="Stopped due to both MCB and SCB settings enabled in groups_vars/all.yml. Please choose one of them and rerun playbook"
  when: weka.backend.mcb == true and weka.backend.scb == true


- name: Get All Container IDs for SCB
  shell: |
    weka cluster container | awk '{print $1}' | sed -e 1d | tr '\n' ',' | sed 's/,$/\n/'
  register: all_scb_container_ids
  when: weka.backend.scb == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ all_scb_container_ids }}
  when: print_debug == true and weka.backend.scb == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']


- set_fact:
    all_cont_ids: "{{ all_scb_container_ids.stdout }}"
  when: weka.backend.scb == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']


- name: Get All Container IDs for MCB
  shell: |
    weka cluster container | grep frontend | awk '{print $1}' | tr '\n' ',' | sed 's/,$/\n/'
  register: all_mcb_container_ids
  when: weka.backend.mcb == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ all_mcb_container_ids }}
  when: print_debug == true and weka.backend.mcb == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']

#
- set_fact:
    all_cont_ids: "{{ all_mcb_container_ids.stdout }}"
  when: weka.backend.mcb == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']


- name: Create SMB Cluster
  shell: |
    weka smb cluster create {{ smb.cluster.name }} {{ smb.ad.domain }} --domain-netbios-name {{ smb.ad.netbios }} ---encryption enabled \
    --container-ids {{ all_cont_ids }} --smb-ips-range {{ smb.net.ips_range }} {{ smb.fs.name }}
  register: create_smb_cluster
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ create_smb_cluster }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']


- name: Validate if SMB Cluster is Online
  shell: weka smb cluster status
  register: check_smb_cluster_status
  until: check_smb_cluster_status.stdout.find("Not Ready") == -1
  retries: 30
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ check_smb_cluster_status }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']


- name: Login into Active Directory
  shell: |
    weka smb domain join {{ smb.ad.users.admin.id }} {{ smb.ad.users.admin.pass }}
  register: login_ad
  until: login_ad is succeeded
  retries: 10
  delay: 420
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ login_ad }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
  # weka smb domain join Administrator --debug --extra-options --domain-ou "jtest.weka.io"
  # "stdout": "Domain join timed out",
  # "stdout_lines": [
  # "Domain join timed out"


- name: Add Default SMB Share
  shell: |
    weka smb share add {{ smb.share.name }} {{ smb.fs.name }} --acl on --encryption cluster_default \
    --internal-path '/{{ smb.share.name }}' --description "{{ smb.share.description }}"
  register: add_smb_share
  when: inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
- debug: msg={{ add_smb_share }}
  when: print_debug == true and inventory_hostname in hostvars[groups['workers'][0]]['ansible_hostname']
  # weka smb share add smb-share-02 smb-fs02 --acl on --encryption cluster_default --internal-path /smb-share-02 --file-create-mask 0744 \
  # --directory-create-mask 0755 --description TEST  0755 and 0744 chagned different value such as 4xx in case of using vars/main.yml


- name: Create Directory to Mount
  file:
    path: "{{ smb.fs.mount_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: yes
  register: create_cifs_dir
- debug: msg={{ create_cifs_dir }}
  when: print_debug == true


# https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html
- name: Mount Ephemeral SMB WekaFS on All Hosts
  mount:
    src: "{{ smb.fs.name }}"
    path: "{{ smb.fs.mount_dir }}"
    opts: ""
    fstype: wekafs
    state: ephemeral
  register: mount_smb_wekafs
- debug: msg={{ mount_smb_wekafs }}
  when: print_debug == true


- name: Change Permission Share Directory
  file:
    path: "{{ smb.fs.mount_dir }}/{{ smb.share.name }}"
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: yes
  register: change_mounted_dir_perm
- debug: msg={{ change_mounted_dir_perm }}
  when: print_debug == true

# how IPA can trust with AD on Freeipa
# ipa-adtrust-install --netbios-name JTEST -a changeme

# Debug command why joining AD takes too long
# adcli join --domain jtest.weka.io --service-name=cifs --computer-name smb-clu01 --host-fqdn jtest.weka.io -v --domain-ou dc=jtest,dc=weka,dc=io -U jomoon
# weka local exec -C smbw bash -ce "chmod 777 /tmp/wekafs/*"
# fio --name=fio-long-1_`hostname` --rw=write --bs=512k --ioengine=posixaio --direct=1 --directory=/mnt/mounted_myshare/ --size=10GB --iodepth=8 --numjobs=1 --group_reporting --runtime=3000000 --time_based
# https://www.notion.so/wekaio/FIP-SMBW-5fc9a2a0c4cd4c8ba9f6a0aafc9840df?pvs=4
