---
- name: Check OS ( Weka SMB )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution_major_version|int >= 8
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky'


- name: Set Facts for Installing Weka Data Platform
  import_tasks: set-install-facts.yml
  tags: deploy, create, install
  when: inventory_hostname in groups['workers']


- name: Set facts for Uninstalling Weka Data Platform
  import_tasks: set-uninstall-facts.yml
  tags: destroy, delete, uninstall
  when: inventory_hostname in groups['workers']


- name: Deploy SMB Backends
  import_tasks: deploy-smb-backend.yml
  tags: deploy, setup, install
  when: ( backend is defined and backend == true ) and inventory_hostname in groups['control']


- name: Setup CIFS Clients
  import_tasks: setup-smb-clients.yml
  tags: setup, create, install
  when: ( client == true ) and inventory_hostname in groups['clients']


- name: Remove CIFS Clients
  import_tasks: uninstall-clients.yml
  tags: remove, delete, uninstall
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']


- name: Destroy SMB Backends
  import_tasks: destroy-smb-backend.yml
  tags: destroy, remove, uninstall
  when: ( backend is defined and backend == true ) and inventory_hostname in groups['control']

