#
- name: Delete text file
  shell: |
    rm -f {{ smb.fs.mount_dir }}/test-smb01.txt
  register: delete_smb_file
  ignore_errors: true
- debug: msg={{ delete_smb_file }}
  when: print_debug == true

#
- name: Umount SMB directory
  shell: |
    umount {{ smb.fs.mount_dir }}
  register: umount_smb_dir
  ignore_errors: true
- debug: msg={{ umount_smb_dir }}
  when: print_debug == true

#
- name: Delete directory to mount SMB
  shell: |
    rm -rf {{ smb.fs.mount_dir }}
  register: delete_smb_dir
  ignore_errors: true
- debug: msg={{ delete_smb_dir }}
  when: print_debug == true

#
- name: Remove SMB Client
  shell: |
    yum remove -y cifs-utils
  register: uninstall_cifs_client
  ignore_errors: true
- debug: msg={{ uninstall_cifs_client }}
  when: print_debug == true

#
- name: Disable Development Repository
  shell: |
    dnf config-manager --set-disabled devel
  register: disable_devel_repo
  ignore_errors: true
- debug: msg={{ disable_devel_repo }}
  when: print_debug == true
