---
- name: Restart minio service
  systemd: name={{ minio_service }} state=restarted daemon_reload=yes
  listen: restart minio

#- name: Waiting for server to come back after reboot
#  local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started delay=10 timeout=300 connect_timeout=300 search_regex=OpenSSH
#  become: no

- name: Wait until minio started
  wait_for:
    host: "{{ ansible_default_ipv4.address | default('localhost') }}"
    port: "{{ minio_port }}"
    delay: 10
  listen: restart minio

- name: Restart nginx
  service: name=nginx state=restarted

- name: Systemd daemon-reload
  systemd: daemon_reload=yes
